### ISSUE TITLE
Remove latest packages RSS in favor of sorting on the API

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#101]

**Comment by jcspencer** [comment]
Could you expand on this?

**Comment by ericmj** [comment]
This https://github.com/hexpm/hex_web/blob/master/lib/hex_web/feeds/router.ex should be replaced by the HTTP API.

**Comment by h4cc** [comment]
Oh, so the feeds are gone? :(
This is what i used for the https://github.com/h4cc/awesome-elixir in combination with https://zapier.com/

What will be the equivalent API call for the RSS Feed of new packages then?

**Comment by ericmj** [comment]
GET /api/packages?sort=inserted_at

**Comment by h4cc** [comment]
Thanks! :+1:
