### ISSUE TITLE
Include reason why authentication failed

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#103]
If authentication failed because a user didn't confirm their email it will be very hard for them to find out why it doesn't work.

**Comment by jcspencer** [comment]
We should be able to add another state (return value) [here](https://github.com/hexpm/hex_web/blob/master/lib/hex_web/api/util.ex#L146) specifically for unconfirmed accounts.

**Comment by jcspencer** [comment]
I'll take this one.
