### ISSUE TITLE
Sort search result by number of downloads and last release date

### ISSUE THREAD

**Issue by awetzel** [hexpm/hex_web#105]
Hello,
It starts to be complicated to make choices between libraries, for instance if you take : 

https://hex.pm/packages?search=xml

exmerl and sweet_xml are similar (both xmerl wrapper), but sweet xml is more used because more complete and useful, but exmerl is the first result because of alphabetic ordering.

Maybe a nice feature would be to sort result : by a combination of last release update and number of last week download and number of overall download.

last release update to give a chance to new libs, but the best metric stay last week download. 

What do you think about that ?

**Comment by awetzel** [comment]
because alphabetic sorting is useful only if you know the library name, and if you know the library name you put it directly in the search input so sorting is not so much useful. So I think sorting may be more useful to help you find a good library for a given purpose

**Comment by ericmj** [comment]
We can add monthly downloads as a column and change the sorting by clicking the columns. It should default to the current sorting though.

**Comment by awetzel** [comment]
Yes adding a column would do the job and is sufficient, thanks for the reply.

But why do you think alphabetic sorting should be default ? It is not an obvious sorting at a point that when I opened the issue (before my comment), I thought that the sorting was shuffle and I use hex.pm almost every day currently (and thank you for it :) ).
Maybe I though the sorting was shuffle because of other similar websites I use together in my projects (clojars,npmjs,rubygems and packagist),  they all shows most recently updated or most download libs first. I understand that the algorithm not being explicit is not so nice (and I dislike that in mentioned websites) but alphabetic is not so explicit either when names are random.

Also the main force  of this type of platform is the total openness, it is also a weakness because packages not maintained anymore or toy projects can stay indefinitely, that's why I give the example of the search "xml" (current I think) where the least useful lib is the first and most useful ones are at the end. In my use case I was looking for the most relevant lib to put my contribution in for open sourcing some XML code, and the usage (click on each lib to see nb of downloads) bugged me. 
A simple column would do the job for this use case since the number of lib is still low but it is meant to growth.

Have a good week end.

**Comment by awetzel** [comment]
And obviously I can help to dev this if you do not have time.

**Comment by jcspencer** [comment]
I believe this should be an easy change to make, as it ultimately only requires modifying `HexWeb.Web.Router.fetch_packages/4` to accept a `sort` parameter (which would refer to a field name) that defaults to sorting by name, and using it in an Ecto query (after ensuring it is safe). This approach would require the user to fully refresh the page to re-organise the contents of the table, but that shouldn't be *too* much of a problem, I wouldn't imagine.

**Comment by ericmj** [comment]
> But why do you think alphabetic sorting should be default ?

It makes sense to sort alphabetically when you search for name. Sorting by last update seems arbitrary, why would a package updated yesterday be more relevant than a package updated last week? Always promoting the most popular is not always ideal either because it means it will keep being the most popular even if better alternatives exist.

> I understand that the algorithm not being explicit is not so nice (and I dislike that in mentioned websites) but alphabetic is not so explicit either when names are random.

What do you mean that names are random?

We can add a column for last update as well but I am afraid we are adding too many columns and the description column will be too short, we will have to see examples of the new layouts. We can probably remove the "latest version" column, that doesn't really feel relevant here.

**Comment by awetzel** [comment]
Yes I agree about the nb of columns, 2 or 3 information per package is a maximum.

What I meant with "random" is that when you choose a name for a library, most of the time the name is random and without meaning (for instance "sweet_xml" or "ecto" or "hex" :) ) : so for a user who are looking for the term "xml", result will appear to be random, even more because all other website sort by some some "relevant" criteria.  
And if you search by name because you know the name, (the case you mentioned where the alphabetic criteria is relevant), then you always tend to have 1, 2 or 3 maximum results and in this case sorting does not matter at all. When you look for a project NOT by name, then alphabetic sorting will appear as a random sorting for the user.

To see the problem in a most obvious way, see : https://www.npmjs.com/search?q=xml or https://www.npmjs.com/search?q=react : more than 2000 results, all projects after the third page of result are toy or dead projects (no update since more than 2 years or 0 dl). Imagine with a sort by name, the projects with names starting with "a" will be the only visible packages on the website, and as a result, all projects looking for traction would start with "00" or "aa" :), and even project which does not care would be forced to embrace a name like that to not disappear :(. 

I agree most popular first is not ideal at all :) (I prefer last update) for the reason you mentioned, but name is kind of worst, since you just have to name your project "0____" or "a____" and decide yourself the place of your project on the website. Not a big issue currently, but the example of the search "xml" shows that it starts to be one. And it is "fairer" to give traction on website to project who has more download or who has just update than to project which are named in order to have traction, that is actually already the case in Hex.pm because of the homepage where highlighted projects are the lastest update or upload projects.

But again, currently there are not so many packages so just adding the nb of download in the search result would be sufficient.

**Comment by awetzel** [comment]
Feature idea in the wild :) : 

Hex.pm could use a community driven reference package list : https://github.com/hexpm/awesome-packages in an Yaml file for instance, by topic or search term, in the fashion of *_awesome repositories (, but with a more opened governance model :) .

And use it to construct its homepage and always explicitly shows packages from the "reference list" first in search results, then last updated sorting to give a chance to newer projects.

**Comment by ericmj** [comment]
Okay, I agree that sorting by number of downloads is better than by name, thanks for convincing me. So I think we should add the monthly downloads column and maybe a latest update date column (lets see how it looks). We should default to sorting by number of downloads but give users the option to sort by name.

> Hex.pm could use a community driven reference package list : https://github.com/hexpm/awesome-packages in an Yaml file for instance, by topic or search term, in the fashion of *_awesome repositories (, but with a more opened governance model :) .

Can you explain some more how that would work? My first thinking is that this is something someone else should do, it's not hex.pm's job to promote packages. Another website that uses hex.pm's API can do that.

**Comment by ericmj** [comment]
@awetzel Are you working on this?

**Comment by awetzel** [comment]
Yes sorry I did not see your answer, thanks to have read my opinion and even more for taking it into account. 

Actually about the idea of a community repository of reference packages by topics, it is an idea I have but i do not have the time currently to work on it. Your are right about that it is not the primary job of hex.pm to promote package, but since it is not only a repository but also a website and a search engine, these kind of website became tool to promote packages in facts.

So my main idea is that there can be a normalized way to give a list of useful package by term : for instance a yaml or/and json or/and xxx specification : 

```json
[
  "sweet_xml": {"relevant_for": ["xml","decoding"], "because": "it makes xmerl easy to use"},
  "cowboy": {"relevant_for": ["webserver","http"]}
]
```

 and that hex.pm could embrace it s role of package spreading tool making use of theses files to customize search results and homepage. 

My main thinking is that this kind of list : https://github.com/h4cc/awesome-elixir is difficult to use, sometimes not relevant, and currently the only way to have a relevant view into the language ecosystem.

**Comment by ericmj** [comment]
hex.pm's main task is just to be a repository and an API interface for clients and other websites to use. The reason we have a website is only for convenience, notice that the website is completely read-only, all user and package related tasks happen through the hex client that is using the HTTP API.

Who should moderate the list of promoted packages? I don't have time or interest in exploring and evaluating every package on hex.pm. This is a job for some other website. We can link to such websites from hex.pm and we can improve our current API if needed to make such websites.

Why would hex.pm be better at promoting packages than https://github.com/h4cc/awesome-elixir?

**Comment by awetzel** [comment]
Yes I agree, it would be crazy for hex.pm to maintain this kind of list, I understand that the website is a side-effect. But I think the issue of having a quality package ecosystem is closely linked with the way to distribute package which is the purpose of hex. If you want to close the debate here, no offense at all :).

If you are interested, I will detail my point and why I think Hex is part of the problem: 

### The problem: open vs approved repository

The way you manage the library repository is central in the development of a functional quality ecosystem, currently I see 3 approaches : 

- a central repo of approved packages : for instance PHP pear or Debian APT repos
- a central repo of approved repositories : for instance Maven Central
- a central and totally open repository : for instance ubuntu PPA / Ruby Gem / Clojars / packagist / HEX

Lesson of 201X: every not opened way of managing a repository does not scale and is an important brake on innovation : Clojars is replacing maven Central for Clojure users, PHP Pear exists only in our memories, Debian Repos are less and less used for the benefit of more opened and up to date (but less safe and robust) repos (ubuntu one or PPA). 

So for Elixir you developed `hex` and it is the way to go : the repository is a tool, and tools must not constraint you but helps you, so no more crazy approval processes :) .

### Problem: package quality management

But with the opening of repositories (and focusing on the real main feature : hosting packages), we lose a key feature : the maintenance of an approved list of good quality and useful packages. So currently no tool exists to handle this problem and this explain the emergence of `*_awesome` repositories which is not nice because not standard and impossible to use in an automated process.

We have now the hindsight of GEM: rubygem allowed a quickly growing ecosystem, but with time, the gem database became bloated and most of the packages (more precisely, those not linked with Rails) are not maintained, unusable with the last version of ruby.

If you developed an application with gem dependencies not linked to rail 2 years ago, it is very challenging  to update it now, and to find what are the current reference libs to use to replace outdated ones... Some of my "not-web" ruby projects died this way.

So my idea is only that if the repo must not maintain a closed list of packages, maybe the package tool must however contain a tool to handle this problem and mainly 2 things : 

- given a package or a list of dependency, get a view of its "life" and relevance
- given a topic get a view of alive and relevant packages 

The "life" and relevancy of a package could be find crossing last update, nb of download recently and presence in users maintained and approved package lists.

Currently, web UI like "hex.pm" (or rubygems.org) or package tools search engines are used this way as a side effect, and because of that they do not include in any ways the main tool to ensure package quality : manual human listing and validation.

### My proposal is not about Hex.pm neither about hex maintaining a list of packages, but about a Hex Ranking feature

My proposal is not well defined, but mainly it is to include "package rank" helpers part of Hex API. 

To do that, Hex could define the standard way to publish a list of relevant packages : for instance an http URL returning a given format. And that Hex can manage a list of approved list URL (to outsource the list maintenance).

You can then customize the reference package list urls, the weight given to nbDownloads/lastUpdate/PresenceInReferenceList, then : 

- Customize package search according to these criteria
- add a new Task to analyse the rate of each dependency of your project and maybe propose alternatives. 

Obviously as this solution is not implemented anywhere, It may be a really stupid idea :) but if you look at rubygems.org and npmjs.com, you can observe that there is a problem to solve here... And as you created Hex, you are the right guy to debate about this :) .

**Comment by awetzel** [comment]
And to answer your last question, Hex is better because it can make a standard about this because hex is the Elixir standard to manage packages, and use this kind of list in package search and analysis tools may be useful.

**Comment by ericmj** [comment]
I'm not convinced we should do this but right now it's just being proposed as "nice thing to have" and sure, it would be nice to have. What we need is concrete proposals of how it's going to work.

* Who is going to manage list, a single person, a group of people or the whole community?
* How is the approval process going to work?
* What criteria should we use to rank packages?
* How should packages be categorized?
* What happens when someone is not happy with their ranking?
* Should we check every package added to the repository (npm has over 100,000 packages), if not how do decide which packages to check?

**Comment by josevalim** [comment]
I agree with @ericmj and @awetzel in the sense that this would definitely be nice to have but I don't think it should be part of Hex at all. Hex is a tool and about infrastructure. Hex and the Hex team should focus on those.

I remember explicitly saying to @ericmj that it would suck if one day someone can own someone's else package because we added a "leave a comment in Markdown" feature that had a bug in the HTML sanitizer which enabled a XSS vulnerability which became the first vector of an attack.

I would rather see efforts like [BEAM Toolbox](http://www.beam-toolbox.com/) become first class and build a community around the packages rather than pushing it to Hex. Once they gain some traction, then we could certainly link to them from Hex, why not.

**Comment by jcspencer** [comment]
I agree completely with @josevalim, Hex is about infrastructure, not about curation or ranking. This kind of tool does not belong in Hex itself, but belongs in a community project. 

Hex has an existing API that would be easy to build a community project around.

**Comment by ericmj** [comment]
Closing this and opening #107 for sorting and displaying package downloads in search.
