### ISSUE TITLE
Sort by and display number of downloads in package search

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#107]

**Comment by parkerl** [comment]
Hey @ericmj I'd be happy to take a stab at this.

**Comment by parkerl** [comment]
@ericmj ahh I forgot you want sorting too. How should this work?

**Comment by ericmj** [comment]
@parkerl It should default to sorting by downloads and you should be able to click "Name" or "Downloads" to change the sorting.

**Comment by parkerl** [comment]
Ok I'm on it.
