### ISSUE TITLE
change username after registering

### ISSUE THREAD

**Issue by matteosister** [hexpm/hex_web#108]
Is there a way to change the username? There is a typo in mine, and I can't find a way to update it.

I'd like to help, but I'm a total newbie of elixir... :smile:

**Comment by ericmj** [comment]
No, you have to create a new user. If you want to reuse your email you can mail support@hex.pm to have them delete your old account.

**Comment by matteosister** [comment]
thanks!

**Comment by matteosister** [comment]
@ericmj many mails after, still nobody answered! :cry:  Do you have any idea on how to delete (and eventually re-use) the same email for a new account?

**Comment by ericmj** [comment]
Your emails were stuck in the spam folder. Your user has been deleted.

**Comment by matteosister** [comment]
many thanks!!!!

Il giorno mer 16 set 2015 alle ore 01:08 Eric Meadows-Jönsson <
notifications@github.com> ha scritto:
