### ISSUE TITLE
Provide copy/pastable snippet on package page for mix.exs entry

### ISSUE THREAD

**Issue by chrismccord** [hexpm/hex_web#110]
It could be for the latest version, i.e.: If I'm viewing httpoison's hex.pm page, I could have a snippet:

    {:httpoison, "~> 0.6"}

That is for the latest major version. Thoughts?

**Comment by ericmj** [comment]
Sounds good. For pre 1.0 packages I think we should generate `{:httpoison, "~> 0.6.1"}` and for post 1.0 we should generate `{:httpoison, "~> 1.6"}`.

**Comment by whatyouhide** [comment]
:+1: very nice addition!

**Comment by jcspencer** [comment]
Something along the lines of this?

```elixir
def print_version(version) do
  %Version{major: major, minor: minor, patch: patch} = version

  case {major, minor, patch} do
    {0, minor, patch} -> "0.#{minor}.#{patch}"
    {major, minor, patch} ->"#{major}.#{minor}"
  end
end

Version.parse("2.1.2")
  |> elem(1)
  |> print_version() # --> 2.1

Version.parse("0.1.2")
  |> elem(1)
  |> print_version() # --> 0.1.2
```

**Comment by ericmj** [comment]
@jcspencer Looks good, but I would match on the result of `Version.parse` instead of piping to `elem`

**Comment by jcspencer** [comment]
```elixir
def display_version({:ok, version}) do
  %Version{major: major, minor: minor, patch: patch} = version

  case {major, minor, patch} do
    {0, minor, patch} -> "0.#{minor}.#{patch}"
    {major, minor, patch} ->"#{major}.#{minor}"
  end
end

Version.parse("2.1.2")
  |> display_version() # --> 2.1

Version.parse("0.1.2")
  |> display_version() # --> 0.1.2
```

Is this more appropriate?

**Comment by jcspencer** [comment]
![screen shot 2015-05-09 at 10 15 24 am](https://cloud.githubusercontent.com/assets/860934/7547617/60a7dc82-f634-11e4-8046-10fb6f2d51a5.png)
This would result in something looking roughly like this.

**Comment by ericmj** [comment]
@jcspencer Beautiful, we should also prepend the version with "~>".

**Comment by Tuxified** [comment]
Since someone mentioned having rebar snippet as well (in the closed PR), I tried something like this:

![screen shot 2015-09-03 at 10 19 58](https://cloud.githubusercontent.com/assets/51889/9653700/b095a4de-5225-11e5-9da7-00920668f25b.png)

Unfortunately, that does pushes the versions and deps info down. If that works for you, I'll make a PR

**Comment by tsloughter** [comment]
Why not move Versions and Dependencies up and to the left of Downloads/Snippets?

**Comment by ericmj** [comment]
@tsloughter idea is great. Make sure to have Dependencies above Versions
because it takes less space.

**Comment by Tuxified** [comment]
That would be something like:

<img width="770" alt="screen shot 2015-09-04 at 09 41 18" src="https://cloud.githubusercontent.com/assets/51889/9678809/35944988-52e9-11e5-89b2-8f5d9108aea0.png">

----------------

BTW, @tsloughter I'm not familiar with rebar version usage, I presumed `0.x.x` for versions smaller than 1.0 and `1.x.*` for versions larger than 1.0 (similar to @ericmj proposal for mix). Is that OK?

```elixir

def mix_snippet_version(%Version{major: major, minor: minor, patch: patch}) when major == 0, 
  do: "~> 0.#{minor}.#{patch}"
def mix_snippet_version(%Version{major: major, minor: minor, patch: _patch}), 
  do: "~> #{major}.#{minor}"

def rebar_snippet_version(%Version{major: major, minor: minor, patch: patch}) when major == 0, 
  do: "0.#{minor}.#{patch}"
def rebar_snippet_version(%Version{major: major, minor: minor, patch: _patch}), 
  do: "#{major}.#{minor}.*"
```

**Comment by tsloughter** [comment]
@Tuxified no, rebar3 doesnt' suppose any of that. It is right as it is in the mock up screenshot, the full version number.

And I meant something slightly different for the layout, but no idea how to show it :). Something like:

```
ecto
------------                                      |-------------------|
Build toold: ...                                  | Downloads:        |
Contributors: ...                                 | 42 ....           |
                                                  | 42 ....           | 
|-----------------|     |------------------|      | 42 ....           |
| Versions:       |     | Dependencies:    |      | 42 ....           |
| x.y.z           |     | dep1             |      |-------------------|                  
| b.x.v           |     | dep2             |
|-----------------|     | dep3             |      |-------------------|
                        |------------------|      | Snippets:         |
                                                  | mix               |
                                                  | rebar3            |
                                                  |-------------------|
```

**Comment by Tuxified** [comment]
Another try then:

![image](https://cloud.githubusercontent.com/assets/51889/9891033/b8dee348-5c03-11e5-8a23-9fc7c4ae3518.png)

Is it ok to leave the grey title part of snippets empty? I don't know how to call them succintly :disappointed:

**Comment by ericmj** [comment]
That looks good. You can just remove the `panel-heading` div: http://getbootstrap.com/components/#panels-basic or call the panel "Config" or something similar.

**Comment by ericmj** [comment]
@Tuxified Any updates? Looking forward to it :)
