### ISSUE TITLE
Doc link for plug_heartbeat version 0.1.0 is broken

### ISSUE THREAD

**Issue by oldfartdeveloper** [hexpm/hex_web#116]
How to reproduce:

1.  Browse https://hex.pm/packages/plug_heartbeat.
1.  On that page, click the link **[docs link](http://hexdocs.pm/plug_heartbeat/0.1.0/)** at the bottom of the page.
1.  Observe you are presented the message "PAGE NOT FOUND".

**Comment by josevalim** [comment]
I think this is the bug we had when docs were being wiped out when sharing a prefix. It has been fixed since then. @whatyouhide can you push the docs for heartbeat again pls?

**Comment by whatyouhide** [comment]
There you go! Sorry :(

**Comment by josevalim** [comment]
@whatyouhide don't be, it was our bug. :)

**Comment by ericmj** [comment]
Ah, I will restore the backups.

**Comment by ericmj** [comment]
Restored backups.
