### ISSUE TITLE
Consider limiting versions on package page

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#120]
Currently, some packages like `phoenix` have many releases (`phoenix` has 31). The list displayed on the package page is not limited, so the list on some packages extends the page tremendously.

One way to solve this would be to limit the page to show only the latest `n` releases, and then show the rest on a separate page, or to simply devise a toggle button to show/hide older versions and their docs.

What are your thoughts on this?

**Comment by ericmj** [comment]
Lets go with showing N releases and then add a link to a separate page.

**Comment by milmazz** [comment]
@ericmj @jcspencer If we use the `collapse` component from Bootstrap we can avoid to show the list of the _oldest versions_  in a separate page.

For example, please assume that `n=2`, we can do something like this:

![screen shot 2015-07-03 at 2 57 27 am](https://cloud.githubusercontent.com/assets/34700/8494970/53362362-212f-11e5-98bb-6c1687cc74b1.png)

If the user wants to see the oldest versions, then just click in the link and :boom: 

![screen shot 2015-07-03 at 2 57 40 am](https://cloud.githubusercontent.com/assets/34700/8494973/56e09f2e-212f-11e5-827c-5e32528b9452.png)


What do you think?

**Comment by ericmj** [comment]
Great idea @milmazz :+1:!

I think the button should stay at the bottom even when uncollapsed. Wdyt?

**Comment by milmazz** [comment]
@ericmj I think I almost have this issue solved, but, if I try to avoid the code duplication in the following section with a new EEx template, that piece of code is not rendered at all.

```html
    <h4>Versions</h4>

    <% show_latest_versions = 2 %>
    <ul class="list-unstyled">
      <%= for release <- Enum.take(@release, show_latest_versions) do %>
        <li>
          <a href="/packages/<%= package.name %>/<%= release.version %>"><strong><%= release.version %></strong></a>
          <span class="text-muted"><%= pretty_date(release.inserted_at) %></span>
          <%= if release.has_docs do %>
            <span class="text-muted">(<a href="<%= safe HexWeb.Release.docs_url(release) %>">docs</a>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>

    <%= if length(@releases) > show_latest_versions do %>
    <div class="collapse" id="oldestVersions">
      <ul class="list-unstyled">
        <%= for release <- Enum.drop(@releases, show_latest_versions) do %>
          <li>
            <a href="/packages/<%= package.name %>/<%= release.version %>"><strong><%= release.version %></strong></a>
            <span class="text-muted"><%= pretty_date(release.inserted_at) %></span>
            <%= if release.has_docs do %>
              <span class="text-muted">(<a href="<%= safe HexWeb.Release.docs_url(release) %>">docs</a>)</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <p><a class="btn btn-primary" role="button" data-toggle="collapse" href="#oldestVersions" aria-expanded="false" aria-controls="oldestVersions">Oldest versions</a></p>
    <% end %>
``` 

With the previous piece of code the feature is working, but if I try [this](https://github.com/milmazz/hex_web/commit/49fff9264b20cdf455a0cb9fa4f7ae8df122f248) I get the following result:

![screen shot 2015-07-29 at 12 17 01 am](https://cloud.githubusercontent.com/assets/34700/8950433/2ffca21a-3587-11e5-91ae-344cc554563b.png)

Any feedback is welcome. Thanks!

**Comment by ericmj** [comment]
Looks like an issue with the safe html engine, please open a PR  with the code you have so I can investigate.
