### ISSUE TITLE
List dependent packages on package page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#123]
Technically only a release has dependents so a package can have different dependents based on which release is considered. For the same reason a package A can depend on B only for a subset of A's releases.

Optional dependencies should also be marked as optional in the dependent list.

Should we only list directly dependent or also include transversally dependent also? Given the following dependency chain: phoenix_ecto -> ecto -> postgrex, should phoenix_ecto be listed as dependent on postgrex? Optional dependencies will also make this more complicated given that we might need to unmark them as optional.

**Comment by jcspencer** [comment]
I'd suggest being able to show each releases dependent packages (defaulting to the latest release), but only include directly dependent packages (as opposed to including transversally dependent packages).

**Comment by ericmj** [comment]
Closing this because it's not on the immediate roadmap and there has been no updates for 6 months.
