### ISSUE TITLE
Recreate download stats materialized views on the fly

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#134]
So that we can run it for any day, not just today. This allows to the rerun yesterdays job before 3AM GMT  the next day.

**Comment by druzn3k** [comment]
I would like to help with this issue, if nobody is already doing it.

**Comment by ericmj** [comment]
Go ahead

**Comment by druzn3k** [comment]
Thanks! In the meantime I could also directly work also on #151, that seems related to me.

**Comment by ericmj** [comment]
Are you still working on this? Otherwise I'll grab it, I need it for another bugfix.

**Comment by druzn3k** [comment]
I was trying, but I'm going too slow because I have not spare time and I'm
not confident enough with ecto. Grab it, I can learn reading your solution
and next time I will be faster. :)
Il 20/ott/2015 06:13 AM, "Eric Meadows-Jönsson" <notifications@github.com>
ha scritto:
