### ISSUE TITLE
Trim invalid UTF8 in search field

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#138]
Will fix exceptions from postgres

**Comment by josevalim** [comment]
You should set up the proper frields in the form to force the browser to submit utf-8. More info here: https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/tag.ex#L114

**Comment by ericmj** [comment]
Note that this is blocking on the phoenix or at least phoenix_html move.

**Comment by jcspencer** [comment]
Could this be solved by using the `accept-charset="UTF-8"` tag on the search form?

**Comment by ericmj** [comment]
I am working on converting to Phoenix now and should be fixed by then.

On Sunday, 6 December 2015, James Spencer <notifications@github.com> wrote:

> Could this be solved by using the accept-charset="UTF-8" tag on the
> search form?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/138#issuecomment-162302865>.
>


-- 
Eric Meadows-Jönsson

**Comment by ericmj** [comment]
Master is using phoenix now so this is up for grabs.
