### ISSUE TITLE
Discuss specification for a simpler registry format

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#140]
Will be less optimized but should be easy to build. Will be useful when running private repositories.

**Comment by jcspencer** [comment]
Could this use a format similar to the log-structured, append-only registry format discussed in #42?

**Comment by ericmj** [comment]
No, the idea is to be much simpler than that. Something that can be built with a small amount of code.

**Comment by jcspencer** [comment]
Should it be an erlang-native format (e.g. ETS) or should it be a globally-supported format (e.g. JSON)?

**Comment by ericmj** [comment]
Neither is good because you will need a lot of code to build those format. CSV or something similar should be used.

**Comment by jcspencer** [comment]
Agreed. Should the format reflect the structure currently used in the ETS-based format, or is structural similarity unimportant?

**Comment by ferd** [comment]
Isn't it more complex to have two formats than a single one?

**Comment by jcspencer** [comment]
Would this be replacing the existing registry format, or co-existing with it?

**Comment by ericmj** [comment]
@ferd It is more complex but the simpler format should be simple enough that it shouldn't matter much. The existing format that will be updated will likely be more complex anyway.

@jcspencer The current format will change but this is another format.

**Comment by ericmj** [comment]
Putting this on hold for now. First step is to provide a new and improved "main" registry format.
