### ISSUE TITLE
Integration with Dash

### ISSUE THREAD

**Issue by Kapeli** [hexpm/hex_web#141]
I'm the developer behind [Dash](http://kapeli.com/dash), an API documentation browser for OS X.

I'd like to allow Dash users to grab docs for hex packages directly from within the app.

What I need:
- [x] A search API for the packages that have docs on hexdocs.pm. Something simple like a substring match over the package names is fine
- [x] Once I have a package name, I need a way to get all the available versions that package has
- [x] Once I have a package name and a version, a way to download the docs for that version (the HTML files).

Are any of these on the roadmap or are there ways to get to them right now? Thank you!

**Comment by pma** [comment]
@Kapeli 

1. List packages that match a give string
$ curl https://hex.pm/api/packages\?search\=plug | jq .

2. Get all available versions of that package
$ curl -s https://hex.pm/api/packages/plug | jq .

3. Get version and check if it has docs
$ curl -s https://hex.pm/api/packages/plug/releases/0.14.0 | jq .

4. Download docs of given version (follow redirect)
$ curl -s -L https://hex.pm/api/packages/plug/releases/0.14.0/docs -o docs.tar.gz

Couldn't find a way to only list packages that have docs (step 1), and the search pattern will match not only on the package name but also the description.

**Comment by Kapeli** [comment]
Awesome. I'm just going to show an error for packages/versions that don't have docs when the user attempts to install them.

**Comment by ericmj** [comment]
All specifications including the HTTP API can be found here: https://github.com/hexpm/hex_web/tree/master/specifications

@Kapeli Can we close this?

**Comment by Kapeli** [comment]
Yes. Closing.

**Comment by thbar** [comment]
@Kapeli is this integration available somewhere? I cannot find the relevant docset, so I'm wondering. Thanks!

**Comment by whatyouhide** [comment]
@thbar on the version of Dash I'm using (3.3.0), you just go to Preferences > Downloads and choose "Hex Docsets" from the list on the left, then you can search for packages on Hex.
