### ISSUE TITLE
"Oldest Versions" button

### ISSUE THREAD

**Issue by eksperimental** [hexpm/hex_web#143]
Hi,
I think that button should read "Older versions", since it's showing all the versions left.
In fact i think we should have something like
"All Versions"
and once clicked, maybe the button could by grayed out and change text to "Recent Versions"

Example:
https://hex.pm/packages/phoenix

**Comment by ericmj** [comment]
I agree on all points, please send a PR.

**Comment by ericmj** [comment]
If possible also try to remove the gap between the old and recent versions.
