### ISSUE TITLE
[Porcelain]: goon executable not found

### ISSUE THREAD

**Issue by eksperimental** [hexpm/hex_web#144]
```sh
$ iex -S mix run
Erlang/OTP 18 [erts-7.0] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
[Porcelain]: goon executable not found
[Porcelain]: falling back to the basic driver
```

should we mention in the README.md that optionally the goon driver should unpacked to the root folder of the project?
https://github.com/alco/goon/releases/latest

**Comment by eksperimental** [comment]
also we should add "/goon" to .gitignore

**Comment by josevalim** [comment]
Shouldn't porcelain have this executable in priv so dependencies don't need to install it separately? /cc @alco

**Comment by alco** [comment]
@josevalim There's a separate executable for each platform: https://github.com/alco/goon/releases/tag/v1.1.1. Including them all with Porcelain is not practical. Also, for the basic use case of spawning a process that doesn't wait for input, the basic driver will work.

**Comment by josevalim** [comment]
Thanks @alco!

**Comment by eksperimental** [comment]
@alco is it technically doable ( i can sit down and do it myself, but not sure if there is any restiction on the hex/mix side), when installing a porcelain as a dependency, or any another app, to detect the OS and download automatically a package as goon?
I'm asking because I m using it myself in an app I'm  writing and I would prefer to do everything automatically.

**Comment by josevalim** [comment]
@eksperimental  it is not possible. Mix does not provide such hooks. Porcelain could provide a task though, if @alco wants one, that could automate that. Then you would just need to call it.

**Comment by eksperimental** [comment]
@josevalim thanks!, I can look into that

**Comment by ericmj** [comment]
The goon executable is not needed.

@alco can we silence the warning? Shouldn't the default be to not say anything, quite annoying when dependency write to stdout just by starting it or maybe it should go through Logger at least?

**Comment by alco** [comment]
I can switch to Logger.debug. Please open an issue on Porcelain's repo.
