### ISSUE TITLE
Add server-side signing of registry file

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#146]
The private key would need to be stored on the hex.pm server so this would only protect against attacks against Amazon S3.

**Comment by jcspencer** [comment]
To verify the registry, the client will need access to the public signing key. Will this be included with the client, or fetched each time?

**Comment by josevalim** [comment]
Elixir will ship with a public key since 1.1. We will be able to re-use it.

**Comment by jcspencer** [comment]
@josevalim What about Hex running on Elixir versions older than v1.1? Should we only check registry signing on Elixir >=1.1?

**Comment by josevalim** [comment]
Yes. They won't be able to check the registry.

**Comment by ericmj** [comment]
@josevalim I think we should use a different key because the one that signs the registry needs to be online. We can do chain though so that the offline key for the hex archive and rebar signs the one we use to sign the registry.

**Comment by josevalim** [comment]
@ericmj that's no problem. We will be able to ship multiple keys with Elixir. :)

**Comment by ericmj** [comment]
The problem is that a single online hosted key compromises all hex and rebar installs since any key shipped with elixir can be used to install.

**Comment by josevalim** [comment]
Yes, I agree. To be clear, all the structure for handling public keys will be in Mix. Hex should just leverage that. And if Hex needs something in particular, we should add it to Mix.

**Comment by jcspencer** [comment]
Who will the Elixir certificate be signed by? Will it be supported on the majority of machines?

**Comment by ericmj** [comment]
It wont be a certificate, just a key that ships with elixir.

**Comment by jcspencer** [comment]
#159 is ready to go, which will add this functionality. Once that's complete, I will open a pull request for client side support.

**Comment by ericmj** [comment]
Hex 0.11.2 added registry verification.
