### ISSUE TITLE
Add naming policy

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#149]
1. Never use another package's namespace. Example: if extending plug namespace your project `PlugExtension`, not `Plug.Extension`, `plug` owns the `Plug` namespace.
2. If your package is an extension or an addition on top of another prefix with the other package's name. Example: extending `plug` should be `plug_extension`

**Comment by whatyouhide** [comment]
Where should this be added?

**Comment by ericmj** [comment]
I'm not sure, which is why opened the issue. Possibly some kind of FAQ page?

**Comment by whatyouhide** [comment]
@ericmj ah ok, I see. Yes, probably a FAQ page could be nice. Should we put that under "Documentation"? I can work on it in the next few days if you want!

**Comment by ericmj** [comment]
Either under "Documentation" or as top-level page. Whatever you think feels/looks best.
