### ISSUE TITLE
mix hex.key remove <key-name> throws 500

### ISSUE THREAD

**Issue by MSch** [hexpm/hex_web#156]
Seems something is broken.

```
% mix hex.user whoami
msch
% mix hex.key list
iMartin
iMartin5K
iMartin5K-2
iMartin5K-3
% mix hex.key remove iMartin5K
Removing key iMartin5K...
Key fetching failed
HTTP status code: 500
** (ArgumentError) argument error
    (stdlib) :io.put_chars(#PID<0.24.0>, :unicode, [[[], %{"status" => 500}], 10])
    (mix) lib/mix/cli.ex:54: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by ericmj** [comment]
Thanks, will check for the logs for what went wrong. If you have the time of the error (and timezone) that would help.

**Comment by MSch** [comment]
Approx 2 minutes before I filed the bug :)

Can still reproduce it, so it definitely happened Wed Sep 16 16:32:37 CEST 2015

**Comment by ericmj** [comment]
Thank you, will investigate.

**Comment by ericmj** [comment]
I have no idea how this issue happened but this commit should fix it: https://github.com/hexpm/hex_web/commit/8a6958a9ab8eefd8d15ce4982a33e3af9b6915d9
