### ISSUE TITLE
Should we really send mail when a package is published?

### ISSUE THREAD

**Issue by henrik** [hexpm/hex_web#158]
Let me know if there's a better place for this discussion.

I find the "…has been published" email superfluous, because `mix hex.publish` already said that it's successfully published. So it's just something to throw away.

For reference, last bit of `mix hex.publish` output:

    Published at https://hex.pm/packages/progress_bar/0.0.10
    Don't forget to upload your documentation with `mix hex.docs`

The email:

    The release progress_bar v0.0.10 has been published, and is now available on Hex.pm.
    
    Note that it may take a while for the documentation on hexdocs.pm to update due to caching.

(Also, the info about the docs seems contradictory. Should I upload explicitly or should I wait for a cache to expire?)

How do others feel about this? Is the email valuable?

If it adds value to some people, maybe it could be a user setting, though it's nicer if those can be avoided.

**Comment by ericmj** [comment]
The email is actually not superfluous since all background jobs haven't been processed when `mix hex.publish` returns. We added the mail because previously when the jobs failed (because of networking errors to S3 or any other reason) the user was not notified and didn't know they should republish. When you get the email you know that everything completed successfully. Maybe we should tweak the message in `mix hex.publish` so that users know they should expect an email?

> (Also, the info about the docs seems contradictory. Should I upload explicitly or should I wait for a cache to expire?)

Thanks for noticing this, the message should only be given when publishing documentation.

**Comment by henrik** [comment]
Eric, thank you for clarifying.

What do you think about an optimistic approach – the mix task could keep claiming it's published, and if the bg jobs succeed no email is sent, but we do send one on failure? There seems to be such an email already: https://github.com/hexpm/hex_web/blob/master/lib/hex_web/email/templates/publish_fail.html.eex

Then the happy case is less noisy, but you're still notified if something goes wrong. If something goes wrong so badly that you don't receive any email, I'm not sure that the absence of a success email will be enough to make people republish, anyway.

**Comment by ericmj** [comment]
> What do you think about an optimistic approach – the mix task could keep claiming it's published, and if the bg jobs succeed no email is sent, but we do send one on failure?

We can possibly do that, would like to hear more opinions on it.

> Then the happy case is less noisy, but you're still notified if something goes wrong.

Is your main issue with the current behaviour that you dislike getting many emails or that just feel that they are unnecessary?

**Comment by henrik** [comment]
> We can possibly do that, would like to hear more opinions on it.

Sounds great.

> Is your main issue with the current behaviour that you dislike getting many emails or that just feel that they are unnecessary?

I guess it's both of those things. I've been pushing new versions fairly frequently and it feels unnecessary to have those mail to clear out afterwards. If there was very often a long delay until they were available, or if it failed very often, I guess it would be a good thing to have. But when things mostly succeed, and quickly, I'd prefer the optimistic "let's assume it worked, and tell them later if it didn't" approach.

**Comment by ericmj** [comment]
Closing this for now. If we get more complaints about excessive email sending I will of course reconsider.

**Comment by henrik** [comment]
Sounds fair.

**Comment by ericmj** [comment]
We will stop sending emails so that the error emails stand out more.

**Comment by henrik** [comment]
Oh, nice. 👍
