### ISSUE TITLE
Reject package pushes with no description

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#162]

**Comment by jcspencer** [comment]
Does this functionality also need to be implemented in the client?

**Comment by ericmj** [comment]
Yep, we need to update the validator on the server and prohibit your from pushing if your forget it in the client.

**Comment by jcspencer** [comment]
I agree. Does Ecto have support for validating JSON fields, or do we need to do it manually?

**Comment by ericmj** [comment]
If you look at `release.ex` there are examples of validating meta fields. It should be a one line code change.

**Comment by fteem** [comment]
@ericmj is this up for grabs? If so, I'd like to take a stab at it.

**Comment by ericmj** [comment]
It's free to take.

On Sun, Oct 18, 2015 at 12:45 PM, Ile Eftimov <notifications@github.com>
wrote:

> @ericmj <https://github.com/ericmj> is this up for grabs? If so, I'd like
> to take a stab at it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/162#issuecomment-149034113>.
>



-- 
Eric Meadows-Jönsson

**Comment by jcspencer** [comment]
This can be closed.
