### ISSUE TITLE
Add autocomplete to search box

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#163]
I think it would be really useful to autocomplete search queries in the search bar. This could be done simply with a query like this:

```elixir
from(p in HexWeb.Package,
        select: p.name)
|> search(search)
|> HexWeb.Repo.all
```

This takes (on average) ~1-2ms per query in my test environment.

**Comment by jcspencer** [comment]
It would also be a good idea to limit the number of responses, as it's overkill to send every single match

**Comment by optikfluffel** [comment]
I guess we should also debounce the input on the client side so we do not fire a request on every keystroke.

**Comment by ericmj** [comment]
There's still a ~200ms roundtrip for people on the other side of the world.

If you want to work on this go ahead but it's not a priority for Hex right now.
