### ISSUE TITLE
Repository mirroring

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#164]
I know it's been on the cards for a while, but I think we need to discuss repository mirroring in more detail. Specifically:

* will clients mirror all packages, or selected packages?
* how will clients fetch a list of packages available for mirroring?
* do storage implementations other than s3 need to be implemented for mirror operators?

There is obviously much more to discuss, but I think this is a good starting point.

**Comment by ericmj** [comment]
Clients will mirror all packages.

Clients can fetch and scan the registry file, with some interval, diff it to what they have locally and fetch new and changed packages.

The mirroring should be independent of the final storage solution so that a new storage can be easily added.

**Comment by jcspencer** [comment]
Should mirrors be notified when a package is updated as to automatically pull it, or should it periodically download the registry?

**Comment by ericmj** [comment]
After the first iteration is implemented we can add pushing with webhooks but for now mirrors need to poll the registry for changes.

**Comment by jcspencer** [comment]
Should mirrors require a hex_web instance to operate? I think it could be wise to have it work in a way that bucket mirroring is separate from running a Hex API server. That way, tools that mirror package tarballs into another region but still rely on the core `hex.pm` API server would be possible.

**Comment by ericmj** [comment]
No, you're right, the mirroring will be a separate project. Also to clarify, the mirror won't use the API server it will just use the CDN to fetch the registry and packages.

**Comment by jcspencer** [comment]
I think we should implement the log-structured registry format before this, as it will be much easier for a mirror to update it's registry and easily identify the diff

**Comment by jcspencer** [comment]
@ericmj what do you think?

**Comment by ericmj** [comment]
Diffing is easy, with a log format it may be slightly easier. The new registry format is still some ways off and we need to support the old one for a quite a while so it shouldn't be a blocker for mirroring.

**Comment by jcspencer** [comment]
That makes sense. How would you go about diffing two ETS tables?

**Comment by ericmj** [comment]
Traverse both ETS tables, build sets of each and then call `Set.difference/2`.

**Comment by ferd** [comment]
There's other fun options for diffing that can require log N time to diff only. I think the last time this was discussed I outlined a possible plan for it.

**Comment by ericmj** [comment]
@ferd Interesting, I didn't know you could implement set difference faster than O(n log n). You would at least need O(n) to load the data set unless you can use functions directly on the ETS table I guess. Can you give us some more details?

Performance is not very important though, we only have 4400 releases so far.

**Comment by ferd** [comment]
well yeah. There's a O(n log n) cost to build the hash tree the first time around, but the cost will be O(log n) per insert, and pretty much O(log n) for the diff (the thing finds entries differing in matching subtrees, so progressive changes are easy to spot and synchronize)

**Comment by jcspencer** [comment]
So something like this?

```elixir

defp to_dict do
  fun = fn
    {{package, version}, _}, acc
        when is_binary(package) and is_binary(version) ->
      acc ++ [{package, version}]
   _, acc ->
     acc
  end

  :ets.foldl(fun, [], get_tid())
  |> Enum.group_by(%{}, fn {package, _version} -> package end)
end

defp compare(a, b) do
  Set.difference(a, b)
end

```

**Comment by ericmj** [comment]
Sort of, don't append to the the end of a list and use `Enum.into(..., HashSet.new)` for creating the set.

**Comment by jcspencer** [comment]
@ferd How would you suggest diffing two ets tables?

**Comment by ferd** [comment]
@jcspencer see https://github.com/hexpm/hex_web/issues/42#issuecomment-118200802

I've got the [merklet](https://github.com/ferd/merklet) repo implementing such a tree, and a closed-source (for now) prototype to live-stream and self-repair updates between them. Diffing them can be a bit tricky to productionize safely, but it's doable.

**Comment by ericmj** [comment]
Just using `MapSet` is good enough. No need to waste time on a fancy diffing algorithm when we don't need it, specially if we are going to change the registry format.

**Comment by ferd** [comment]
yeah the fancy diffing is mostly worth it when you want to diff over the network without sharing the entire data set every time. It lets you run very efficient diffs frequently (even multiple times a second between peers if you want to) without blowing up your bandwidth.

**Comment by jcspencer** [comment]
For now, I think the best implementation would be @ericmj's idea of using a HashSet and using `Set.difference/2`, like so:

```elixir
defp collect(tid) do
  fun = fn
    {{package, version}, _}, acc
        when is_binary(package) and is_binary(version) ->
      [{package, version}] ++ acc
    _, acc ->
     acc
  end

  :ets.foldl(fun, [], tid)
  |> Enum.into(HashSet.new)
end

defp diff(old, new) do
  a = collect(old)
  b = collect(new)

  HashSet.difference(a, b)
end
```

In the future as the registry grows, however, I think using a more efficient diffing technique (such as @ferd's suggestion) would be a better idea, to reduce network load, etc.

**Comment by jcspencer** [comment]
I'm happy to start the implementation of a separate project to handle mirroring. Before I begin, I've got a few questions:

* Will this project need to have HTTP functionality? (i.e. should it be built as a web service)
* Since functionality will be shared between this project and the existing *hex* and *hex_web* projects, should shared logic be split into a separate project that is mutually depended upon, or should the existing logic be reimplemented again?

**Comment by ericmj** [comment]
The more efficient diffing technique would be the new registry format. It will by design be a diff.

**Comment by jcspencer** [comment]
@ericmj I think (for now), we can work with the existing registry format as a placeholder, and replace it later, as I don't think we'll be able to migrate to the new registry format extremely quickly (I think)

**Comment by ericmj** [comment]
> Will this project need to have HTTP functionality? (i.e. should it be built as a web service)

I'm not sure how this should work yet. But we probably need a pluggable backend where people can add functionality they need. We can ship with a few defaults, like a plug http backend or something that can upload to FTP, S3, etc.

> Since functionality will be shared between this project and the existing hex and hex_web projects, should shared logic be split into a separate project that is mutually depended upon, or should the existing logic be reimplemented again?

There is basically nothing to share for the first registry format so there is nothing to reimplement. The second registry format may be able to share more (because the code is more complicated) but unfortunately hex cannot use dependencies so we can't really share code anyway.

> I think (for now), we can work with the existing registry format as a placeholder, and replace it later, as I don't think we'll be able to migrate to the new registry format extremely quickly (I think)

Yes.

> I'm happy to start the implementation of a separate project to handle mirroring.

I think an intern from ESL is working on this. I asked him/her to read this discussion and drop a comment here so that everyone knows it is being worked on. Unfortunately I have no way of contacting the intern directly :(. /cc @brucify

**Comment by jcspencer** [comment]
Do you have an existing implementation of the new registry format of which can be use?

-- 
James Spencer

On 16 October 2015 at 12:11:58 pm, Eric Meadows-Jönsson (notifications@github.com) wrote:

Will this project need to have HTTP functionality? (i.e. should it be built as a web service)

I'm not sure how this should work yet. But we probably need a pluggable backend where people can add functionality they need. We can ship with a few defaults, like a plug http backend or something that can upload to FTP, S3, etc.

Since functionality will be shared between this project and the existing hex and hex_web projects, should shared logic be split into a separate project that is mutually depended upon, or should the existing logic be reimplemented again?

There is basically nothing to share for the first registry format so there is nothing to reimplement. The second registry format may be able to share more (because the code is more complicated) but unfortunately hex cannot use dependencies so we can't really share code anyway.

I think (for now), we can work with the existing registry format as a placeholder, and replace it later, as I don't think we'll be able to migrate to the new registry format extremely quickly (I think)

Yes.

I'm happy to start the implementation of a separate project to handle mirroring.

I think an intern from ESL is working on this. I asked him/her to read this discussion and drop a comment here so that everyone knows it is being worked on. Unfortunately I have no way of contacting the intern directly :(. /cc @brucify

**Comment by ericmj** [comment]
No, the specification isn't even finalized.

**Comment by dexsda** [comment]
Hello, I'm the intern mentioned by @ericmj. I had a lot of different things to work on/finalize before I could get into this project, but these should be out of the way for now.

@jcspencer , did you attempt starting your implementation already?

For future reference, you can contact me on karol.urbanski [at] erlang-solutions.com.

**Comment by jcspencer** [comment]
I haven't currently started on an implementation, but I'm happy to assist now that you're available.

Do you have a rough idea of how you want to tackle to problem?

-- 
James Spencer


On 3 November 2015 at 3:30:05 am, Karol Urbański (notifications@github.com) wrote:

Hello, I'm the intern mentioned by @ericmj. I had a lot of different things to work on/finalize before I could get into this project, but these should be out of the way for now.

@jcspencer , did you attempt starting your implementation already?

For future reference, you can contact me on karol.urbanski [at] erlang-solutions.com.

**Comment by dexsda** [comment]
In broad terms, I'd start by creating a skeleton project (as Eric wants); creating basic methods of finding if there's a new update (using the diffing snippets here); build something that can mirror the required packages when ran, starting with a simple mirror to the local machine; and expanding that to use more sophisticated methods like mirroring to FTP or S3 and on polling techniques.

The biggest thing I can see right now is making sure we can easily replace the implementation of the diffing methods.

I'll be playing around with hex_web and hex today, see how the things look both on the frontend and backend. Eric suggested fetching the tarballs from the CDN instead of using the API, I believe? 

One thing that needs to be decided on at this stage is whether we want this project as a web service (as you already asked) or treat it as more of a pluggable backend thing you just run on the machine you want to be mirroring the systems. Obviously, with a backend implementation adding a web service layer doesn't seem too difficult, but I think it might save us some bother if we start with the understanding what we want the final product to look like, in broad terms.

If all goes well with my 'playing around' I'll create the skeleton project on github and send you the collaborator link today; if not, I'll probably post here with questions that pop up and work on getting that repo up around the weekend.

I'm very happy to have someone willing to assist, and since I'm still 'getting into' elixir as a whole, I'll appreciate any tips or criticism you might have once we get this thing going. Thank you!

**Comment by ericmj** [comment]
> Eric suggested fetching the tarballs from the CDN instead of using the API, I believe?

Yes, that's the only way to fetch them.

> If all goes well with my 'playing around' I'll create the skeleton project on github and send you the collaborator link today; if not, I'll probably post here with questions that pop up and work on getting that repo up around the weekend.

Looking forward to it :)

**Comment by ericmj** [comment]
> One thing that needs to be decided on at this stage is whether we want this project as a web service (as you already asked) or treat it as more of a pluggable backend thing you just run on the machine you want to be mirroring the systems. Obviously, with a backend implementation adding a web service layer doesn't seem too difficult, but I think it might save us some bother if we start with the understanding what we want the final product to look like, in broad terms.

What is the difference between a web service and a backend here?

**Comment by brucify** [comment]
Hi 

@yohaneskuma will take over from @dexsda now. Beow is a summary of the tasks. The most important in **Bold**, things can that come later in *Italic*.

**Fetching package registry**
* Client is able to fetch and scan the registry file, with some interval.
* Mirrors won't use the API server, it will just use the CDN to fetch the registry and packages.
* A new registry format is under construction, so the project needs to keep in mind. For now it is enough to support the current format.
* *Add pushing with webhooks, so mirrors are notified when a package is updated.*

**Fetching packages**
* Client is able to mirror all packages.
* Client is able to fetch new and changed packages.

Ability to sync between mirrors
* Mirrors don't require a hex_web instance to operate.
* Client is able to diff it to what they have locally. We need to determine a final diff algorithm.
* Set up Hex mirrors on different S3 availability zones.

*Performance*
* *Performance is not very important at this moment, we only have 4400 releases so far.*

Other
* We will need to have more discussion whether to design it as web service or not.


Please let us know if you have changes to the tasks above or any higher priority tasks you would like us to work on.

**Comment by ericmj** [comment]
Looks good. This is done already "Set up Hex mirrors on different S3 availability zones.".

**Comment by brucify** [comment]
Now the discussion is concluded. The implementation is at https://github.com/ieug/HexMirror/tree/develop_hex_mirror

Further discussions can be reported there.

**Comment by brucify** [comment]
The project is available for testing at 

https://github.com/ieug/HexMirror/tree/develop_hex_mirror#getting-started

Feedback wanted!
