### ISSUE TITLE
Document mirrors

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#168]
Currently we have three official sources for packages, in the future we will have mirrors. They should be documented somewhere on the website.

**Comment by jcspencer** [comment]
Perhaps something like this could be a starting point?

| Name | Location | URL | Official? |
|----------|------------|--------|-------------|
| America (default) | US East | https://s3.amazonaws.com/s3.hex.pm | Yes |
| Europe | Europe West | https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm | Yes |
| Asia | Southeast Asia | https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm | Yes |

**Comment by jcspencer** [comment]
As well as instructions on applying them, of course

**Comment by ericmj** [comment]
That looks great, instructions would be useful as well. The exact locations are "US East (Northern Virgina)", "Europe West (Ireland)", "Southeast Asia (Singapore)".

**Comment by jcspencer** [comment]
I think this should be close to what would be required. Please leave some comments if you see fit.
--

# Mirrors

Hex packages and archives are distributed (mirrored) in various locations. Using a nearby server will speed up your download, and also reduce the load on the central server.

*Note:* By default, the American (US East) bucket is used by Hex clients.

## Usage

To permanently select a mirror, simply run the following command in a shell session (where `url` is one of the mirror URLs shown below).

**Example**: `$ mix hex.config cdn_url https://s3.amazonaws.com/s3.hex.pm`

To temporarily select a mirror, simply prepend `HEX_CDN=<url>` to any Hex command on the shell (where `url` is one of the mirror URLs shown below).

**Example**: `$ HEX_CDN= mix hex.registry`

## Available mirrors

| Region | Location | URL | Official? |
|----------|------------|--------|-------------|
| America (default) | US East (Northern Virginia) | https://s3.amazonaws.com/s3.hex.pm | Yes |
| Europe | Europe West (Ireland) | https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm | Yes |
| Asia | Southeast Asia (Singapore) | https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm | Yes |

You can test your connection latency for each AWS region [here](http://www.cloudping.info/).

**Comment by ericmj** [comment]
Looks great! Please send a PR.

**Comment by manveru** [comment]
Is it just me, or are all the links broken? I'm getting:

    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>16B948AADBFA7F98</RequestId><HostId>doGVZ0yqNVLaXICPI7Su1jYe9HHhNnvU/slLOTmuxXeaL7hbJGEkefhMPWwyO65wI8VUSkp/fa0=</HostId></Error>

**Comment by josevalim** [comment]
You can't access them at the root, there is nothing to serve there.
@ericmj maybe we should include some URL for people to try? If so, which
one?


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by manveru** [comment]
Well, I originally came here because the download link at
https://hex.pm/docs/usage is broken. Any alternatives for that?

On Mon, Nov 2, 2015 at 12:05 PM, José Valim <notifications@github.com>
wrote:

> You can't access them at the root, there is nothing to serve there.
> @ericmj maybe we should include some URL for people to try? If so, which
> one?
>
>
> --
>
>
> *José Valim*
> www.plataformatec.com.br
> Skype: jv.ptec
> Founder and Director of R&D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/168#issuecomment-152989194>.
>



-- 
Michael Fellinger

**Comment by josevalim** [comment]
@manveru that seems a broken link regardless of this issue. :) Can you please open up another report? Do you want to publish an Elixir project or an Erlang one?

**Comment by ericmj** [comment]
We should remove that link because we no longer suggest installing mix separately now that rebar3 supports hex. Why are you looking for the mix download?

Also closing this issue now because mirrors are documented.
