### ISSUE TITLE
Add direct link to non-versioned hexdocs from package page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#169]
Saw questions about linking to the latest to hexdocs version, we have no direct link to it so unless you know about it will be hard to find.

**Comment by fteem** [comment]
I would like to tackle this, but I am not sure what exactly needs to be done? Where do we want the links to appear? Does it mean every package needs to have a link to the non-versioned hexdocs?

**Comment by ericmj** [comment]
Every package should have a link to the non-version hexdocs (https://hexdocs.pm/a_package) somewhere on the package page. I don't know the best place for the link so it's open to decide for the contributor :).

**Comment by fteem** [comment]
This can be closed, got resolved in #186
