### ISSUE TITLE
Add mirror documentation for rebar3

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#173]
This page: https://hex.pm/docs/mirrors

/cc @tsloughter

**Comment by jcspencer** [comment]
In order to set the URL permanently, we can run `$ rebar3 hex config cdn_url <url>`, but AFAIK, we can't do it temporarily. If this is correct, I can write up these docs.

**Comment by tsloughter** [comment]
That is correct.

**Comment by ericmj** [comment]
Ping?

**Comment by tsloughter** [comment]
Pong. Will look soon.

**Comment by tsloughter** [comment]
What is `mix hex.registry` in the example? That isn't in the mix tasks documentation.

**Comment by tsloughter** [comment]
Ours is a little different and odd: https://github.com/hexpm/hex_web/pull/182

We allow overriding the cdn for fetching with `rebar_package_cdn` in the rebar3 configs. We only look at the hex config when using the rebar3 hex plugin for publishing or doing other hex api work.

**Comment by ericmj** [comment]
`mix hex.registry` is wrong, it should be `mix deps.get` or something similar.
