### ISSUE TITLE
Add category to libs to make easy find it

### ISSUE THREAD

**Issue by victorlcampos** [hexpm/hex_web#174]
Hi, a good feature of www.ruby-toolbox.com is search by category.
It's allow you to compare libs from the same category and make choose easyer.

![image](https://cloud.githubusercontent.com/assets/1539610/10716092/1c1285f8-7b14-11e5-9516-5e38d019466d.png)

![image](https://cloud.githubusercontent.com/assets/1539610/10716091/065d691c-7b14-11e5-948e-6bac78a32239.png)

**Comment by ericmj** [comment]
This has been discussed a few times before and the conclusion has been that full text search of the package description is good enough for finding packages for now. The problem with categories is that they need moderation and the hex developers and admins (me) need to focus on the core goals of Hex. Instead I would like to suggest working on an external site, which uses Hex's HTTP API, that can have categories, voting, comments and anything else you would like to make it easier to find and browse packages.

See this thread for more discussion: https://groups.google.com/d/msg/elixir-lang-core/GAY8RC8bRNw/2MLmLNjoAgAJ

**Comment by victorlcampos** [comment]
![image](https://cloud.githubusercontent.com/assets/1539610/10716646/f0f410a4-7b26-11e5-8f77-5c2248ac3a79.png)

**Comment by victorlcampos** [comment]
Where could I find hex http api?

**Comment by ericmj** [comment]
https://github.com/hexpm/hex_web/tree/master/specifications

On Sun, Oct 25, 2015 at 5:46 PM, Victor Campos <notifications@github.com>
wrote:

> Where could I find hex http api?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/174#issuecomment-150941153>.
>



-- 
Eric Meadows-Jönsson

**Comment by victorlcampos** [comment]
Thx
