### ISSUE TITLE
Cannot find docs that were published

### ISSUE THREAD

**Issue by HashNuke** [hexpm/hex_web#175]
```
★ MIX_ENV=docs mix hex.docs
Docs successfully generated.
View them at "doc/index.html".
[#########################] 100%
Published docs for hound v0.7.4
Hosted at http://hexdocs.pm/hound/0.7.4/

~/projects/hound:master 
★ mix hex.info hound 0.7.4
hound v0.7.4
  Documentation at: http://hexdocs.pm/hound/0.7.4/
  Dependencies:
    httpoison: ~> 0.7
    poison: ~> 1.4
```

Visiting http://hexdocs.pm/hound/0.7.4 redirects to http://hexdocs.pm/hound/0.7.4/README.html which says "page not found". The same error when visiting without version in the url http://hexdocs.pm/hound/

**Comment by milmazz** [comment]
Review your ExDoc configuration, instead of `readme` please use the `extras` option.

```
docs: [extras: ["README.md"], main: "README",...]
```

**Comment by HashNuke** [comment]
@milmazz Yes just noticed that it was using the older config updated it thanks.

**Comment by HashNuke** [comment]
@milmazz I published a new version after updating the package info. Both http://hexdocs.pm/hound/0.7.5 and http://hexdocs.pm/hound still redirect to README.html.

The `main` is set to `extra-readme` - https://github.com/HashNuke/hound/blob/master/mix.exs#L14
and the file is available at http://hexdocs.pm/hound/0.7.5/extra-readme.html

**Comment by HashNuke** [comment]
@milmazz it was the cloudflare caching I guess. Works now.
