### ISSUE TITLE
Add latest version number to API packages list?

### ISSUE THREAD

**Issue by henrik** [hexpm/hex_web#187]
It would simplify things for http://toolbox.elixir.pm if this was included without having to look at each individual package. 

Would you be open to a PR?

**Comment by ericmj** [comment]
Don't you need the individual packages for anything else? I am hesitant because we need to fetch all releases for a package to figure out the latest version. We might optimize by caching the latest version on the package table or implementing the version compare as a function in postgres.

**Comment by henrik** [comment]
Hm, comparing the API responses, the "releases" list seems to be the only thing missing from the list as compared to the individual package info. And I don't expect to need any details of the releases, beyond the current version number.

Would we have to implement version compare? Maybe we could just look at the associated release with the highest id? Maybe that could be a fast-enough query, not sure.

**Comment by ericmj** [comment]
I don't want to do the extra association call, it's expensive just to get the latest version. If you want the latest version you need to fetch the individual packages and get the latest version from that.

**Comment by henrik** [comment]
Yeah, makes sense. Do you think caching the value is something worth considering, or would you rather skip that? I would totally understand – just wanted to check what might be done on the Hex.pm side before I start on this.

**Comment by henrik** [comment]
Just noticed that https://hex.pm/packages shows latest version, so maybe a cached number could come in handy there.

**Comment by ericmj** [comment]
https://hex.pm/packages is hit a lot less often than the API. I think caching would mostly complicate things at this point.

**Comment by henrik** [comment]
Alright, no worries! Thanks for entertaining the discussion all the same :) I'll close the ticket.
