### ISSUE TITLE
robots.txt and sitemap.xml

### ISSUE THREAD

**Issue by ntrepid8** [hexpm/hex_web#190]
Is  Google crawling hexdocs.pm?  I am getting 404s for both of these:

- <http://hexdocs.pm/sitemap.xml> 
```
$ curl http://hexdocs.pm/sitemap.xml -v > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.28.24.63...
* Connected to hexdocs.pm (104.28.24.63) port 80 (#0)
> GET /sitemap.xml HTTP/1.1
> Host: hexdocs.pm
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Mon, 23 Nov 2015 17:47:58 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
...
```
- <http://hexdocs.pm/robots.txt>
```
$ curl http://hexdocs.pm/robots.txt -v > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.28.24.63...
* Connected to hexdocs.pm (104.28.24.63) port 80 (#0)
> GET /robots.txt HTTP/1.1
> Host: hexdocs.pm
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Mon, 23 Nov 2015 17:49:27 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
...
```

Should these be produced to make it easier for search engines to index hexdocs.pm?  This may not be an issue, but sometimes it seems like Google is not able to find docs even with a very specific search.  For example Google has trouble with finding the docs for `amqp`:

![screenshot 2015-11-23 12 44 18](https://cloud.githubusercontent.com/assets/482948/11344549/14493078-91e0-11e5-8352-d61706216210.png)

Even though the `amqp` package docs are hosted on hexdocs.pm:

![screenshot 2015-11-23 12 46 08](https://cloud.githubusercontent.com/assets/482948/11344593/44def8f8-91e0-11e5-9d2c-0ea718804ba0.png)

**Comment by ericmj** [comment]
We don't have a sitemap or robots file for either hexdocs or hex. If you would like to contribute that would be greatly appreciated.

Google is indexing both hex and hexdocs though: https://www.google.se/#q=hexdocs+amqp

**Comment by ntrepid8** [comment]
Ok, I'll take a crack at it :)

**Comment by milmazz** [comment]
@ntrepid8 You can also try with: `site:hexdocs.pm amqp`

![capture](https://cloud.githubusercontent.com/assets/34700/11345281/7f65a3be-91db-11e5-89d1-4ed2c4b48910.PNG)

**Comment by ntrepid8** [comment]
@milmazz yep that does work but it's not really the first thing that most people try.  I'm thinking it will make it easier for others to get into Elixir if they can just Google for the search results.

**Comment by jcspencer** [comment]
I think we also need to add a meta description tag to both package pages, as well as the main page. It will make search results much clearer.

-- 
James Spencer
Sent with Airmail

On 24 November 2015 at 5:13:08 am, Milton Mazzarri (notifications@github.com) wrote:

@ntrepid8 You can also try with: site:hexdocs.pm amqp

**Comment by ericmj** [comment]
Thank you @bjfish!
