### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by Nicd** [hexpm/hex_web#191]
The EU [Data Protection Directive](https://en.wikipedia.org/wiki/Data_Protection_Directive) states that personal data of users may only be used

> * when the data subject has given his consent.
> * when the processing is necessary for the performance of or the entering into a contract.
> * when processing is necessary for compliance with a legal obligation.
> * when processing is necessary in order to protect the vital interests of the data subject.
> * when processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller or in a third party to whom the data are disclosed.
> * when processing is necessary for the purposes of the legitimate interests pursued by the controller or by the third party or parties to whom the data are disclosed, except where such interests are overridden by the interests for fundamental rights and freedoms of the data subject. The data subject has the right to access all data processed about him. The data subject even has the right to demand the rectification, deletion or blocking of data that is incomplete, inaccurate or isn't being processed in compliance with the data protection rules. (art. 12)

Additionally:

> The data subject has the right to be informed when his personal data is being processed. The controller must provide his name and address, the purpose of processing, the recipients of the data and all other information required to ensure the processing is fair. (art. 10 and 11)

Personal data is defined as

> "any information relating to an identified or identifiable natural person ("data subject"); an identifiable person is one who can be identified, directly or indirectly, in particular by reference to an identification number or to one or more factors specific to his physical, physiological, mental, economic, cultural or social identity;"

In short, if the person can be identified from the data directly or indirectly, it is considered personal data. As such, email addresses would fall under personal data for many people. To be on the safe side, I propose to:

1. add a privacy policy (there are many templates online), and
2. add a prompt to either `mix hex.user register` or some text in the verification email to indicate to the user that by continuing they pinky swear to have read the privacy policy and consent to the usage of their data.

**Comment by ericmj** [comment]
This some information I think can be useful in a privacy policy:

* The personal data we store in the database is username and email
* Requests to the API server and CDN are logged which includes IP address and user agent
* Both hex.pm and hexdocs.pm runs Google Analytics
* hex.pm, hexdocs.pm and the CDN is hosted in the USA, the CDN also has mirrors in Ireland and Singapore, the CDN is also public so anyone can keep copies of it

We can try modelling on other package managers' privacy policies:

NPM has a policy https://www.npmjs.com/policies/privacy.
I can't find any other pacakge managers that has privacy policies.

**Comment by ericmj** [comment]
Step 1 will be done here https://github.com/hexpm/hex_web/pull/274. Still need to do step 2 to add a prompt when registering a user.

Also ccing @tsloughter because the prompt needs to be added to the rebar3 plugin also.

**Comment by ericmj** [comment]
Closing this in favour of the PR. Step 2 should be done at https://github.com/hexpm/hex, PRs appreciated.
