### ISSUE TITLE
Front-end Development for Template Redesign

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#193]
I'm converting the PSD to front-end now. I choose to do that in parallels with Gulp because of speed, once the project doesn't have livereload or automatic template compile.

Any concern?

**Comment by pragmaticivan** [comment]
Another Question: How bad/hard would be to have the front-end part of the project outside and start using it as an API consumer?

**Comment by pragmaticivan** [comment]
You guys can track the process here: http://pragmaticivan.github.io/hex-web-template/

**Comment by ericmj** [comment]
> I'm converting the PSD to front-end now. I choose to do that in parallels with Gulp because of speed, once the project doesn't have livereload or automatic template compile.

You can use whatever you want to develop, but I don't want to merge a dependency on gulp.

> Another Question: How bad/hard would be to have the front-end part of the project outside and start using it as an API consumer?

Not sure if it is worth the extra complexity. What would the benefits be?

**Comment by pragmaticivan** [comment]
| You can use whatever you want to develop, but I don't want to merge a dependency on gulp.

The idea is just develop this fast and move the front-end using copy/past if that's the case. The velocity of development using something like gulp is way bigger.

| Not sure if it is worth the extra complexity. What would the benefits be?

No big deal, but if the front-end is out would be easier to test and deploy just the front-end part. And for the future migration of phoenix would be easier, because we will already have the endpoints where the front-end is getting the data.

**Comment by pragmaticivan** [comment]
[WIP] Just for continuous feedback Here are some of the pages I'm working on:

- Home: http://pragmaticivan.github.io/hex-web-template/
- Package List: http://pragmaticivan.github.io/hex-web-template/packages.html
- Package View: http://pragmaticivan.github.io/hex-web-template/package-view.html

**Comment by pragmaticivan** [comment]
* About Page: http://pragmaticivan.github.io/hex-web-template/about.html

**Comment by josevalim** [comment]
That looks fantastic @pragmaticivan! My only concern so far is that the homepage fonts look really big. Running at 90% size definitely looks better here. The "Getting Started" section still looks big though and it could use a bit more of spacing. :)

Finally, what if the line that divides the headers and packages at the bottom is made of light grey?

**Comment by pragmaticivan** [comment]
Cool, I also have some concerns at Home Page, bottom line of MOST DOWNLOADED,  NEW PACKAGES and RECENTLY UPDATED is making my life hard for responsive layout. just because It's 100% wide. I'm thinking about to reduce the line or remove this.

The template is almost 100% responsive. The front-end is not ready, It's just a work in progress. I need to improve a lot of things, and I agre that I definitely need to do some work in the fonts.

**Comment by ericmj** [comment]
@pragmaticivan master uses phoenix now so your workflow should be better now with the automatic reloads and recompiles. I hope this wont cause you too many conflicts, the templates were essentially unchanged, they just moved to a new location.

**Comment by pragmaticivan** [comment]
Thanks @ericmj I'm working on moving my front-end project inside a branch here.

**Comment by pragmaticivan** [comment]
@ericmj I'm not sure if you had this issue before. I want to use SASS in this project, I added `"sass-brunch": "^1.9.1",`. Seems to compile well. But I'm having trouble trying to add the file in the template. Sorry, I'm newbie with that, do you you have any example, there's not a lot of info about that. Just trivial articles about how to install, but never about how to call inside the template.
