### ISSUE TITLE
Missing readme.html on versioned docs url

### ISSUE THREAD

**Issue by seantanly** [hexpm/hex_web#194]
Just did a `mix hex.docs` to update existing docs with the latest ex_docs (0.11.1), and I'm getting a missing `readme.html`.

This doesn't load,
http://hexdocs.pm/paratize/2.1.1/readme.html

This does, though they should be the same? 2.1.1 is the latest version.
http://hexdocs.pm/paratize/readme.html

I didn't have this problem with another hex package docs which I updated the same way. Is this a cache problem?

**Comment by josevalim** [comment]
The README loads here so it is a cache problem. Give it 24h and if it doesn't work out please reopen. :)

**Comment by seantanly** [comment]
Thanks, will do.

VPNed to a different geo location and it loads there. Indeed, it's probably
the CDN cache. :)

**Comment by ericmj** [comment]
Opened an issue for a way to better handle this: https://github.com/hexpm/hex_web/issues/195
