### ISSUE TITLE
Purge hexdocs.pm pages from CDN on new publish

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#195]
Currently hexdocs.pm is an S3 bucket with CloudFlare in front. When new documentation is pushed the old version can be cached on CloudFlare and it's confusing to users that the hexdocs doesn't immediately update. We can make an API request to CloudFlare to manually purge the required pages from the cached.

We may change to Fastly as CDN soon so we should hold on with this until we know. Fastly also has API for purging pages.

**Comment by jcspencer** [comment]
Will occur after the package has sucessfully published, or before the new files are pushed up?

Also, do these APIs allow the specific files to be flushed, or does the entire cache need to be purged?

-- 
James Spencer
Sent with Airmail

On 2 December 2015 at 3:01:40 am, Eric Meadows-Jönsson (notifications@github.com) wrote:

Currently hexdocs.pm is an S3 bucket with CloudFlare in front. When new documentation is pushed the old version can be cached on CloudFlare and it's confusing to users that the hexdocs doesn't immediately update. We can make an API request to CloudFlare to manually purge the required pages from the cached.

We may change to Fastly as CDN soon so we should hold on with this until we know. Fastly also has API for purging pages.

**Comment by ericmj** [comment]
It needs to happen after or there will be a race condition.

Purging the whole cache is not an option because it will make the cache useless.

**Comment by jcspencer** [comment]
I'm working on an application at the moment that will be interacting with Fastly. After the new year (early January), I'm planning to build an elixir library to do so, so I will be able to build this functionality then, if it suits

On 6 December 2015 6:27:30 PM LHDT, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>It needs to happen after or there will be a race condition.
>
>Purging the whole cache is not an option because it will make the cache
>useless.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/195#issuecomment-162284750

-- 
James Spencer

**Comment by jcspencer** [comment]
Note to self: we can set the x-amz-meta-surrogate-key header on s3 files when uploaded, that way we can tag all files associated with a documentation bundle with a key such as 'ecto/1.2.3'. 

That way, we don't need to call a purge for each file, but rather just one call that covers every file in a documentation bundle.

On 6 December 2015 2:27:30 PM GMT+07:00, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>It needs to happen after or there will be a race condition.
>
>Purging the whole cache is not an option because it will make the cache
>useless.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/195#issuecomment-162284750

-- 
James Spencer

**Comment by jcspencer** [comment]
Here is a (very) rough prototype: https://gist.github.com/jcspencer/58338239c99cb867ae3e

This only implements basically purge_all (service specific) and purge_key (service/surrogate key specific) functions, which I assume should be enough for Hex
