### ISSUE TITLE
Only allow key authentication on requests that doesn't require password authentication

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#196]

**Comment by ericmj** [comment]
Today all authenticated requests allow you to use both key and username/password authentication except for the request that creates new keys. All requests except `POST "keys"` should only allow key authentication.

**Comment by jcspencer** [comment]
This is a fairly easy fix, but it may break a lot of third-party clients that use the Hex API. If it were to be introduced, we need to make sure there is a change window, along with good documentation on using key authentication.

**Comment by ericmj** [comment]
I think it should be fine. The only clients that need authentication is
those that publish packages. That should only be the mix and rebar3 client
and they already do it correctly. It is also documented as only key
authentication supported.

On Sunday, 6 December 2015, James Spencer <notifications@github.com> wrote:

> This is a fairly easy fix, but it may break a lot of third-party clients
> that use the Hex API. If it were to be introduced, we need to make sure
> there is a change window, along with good documentation on using key
> authentication.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/196#issuecomment-162301640>.
>


-- 
Eric Meadows-Jönsson
