### ISSUE TITLE
Display Elixir version requirement for packages

### ISSUE THREAD

**Issue by alco** [hexpm/hex_web#20]
Here's a package with lots of versions: https://hex.pm/packages/exrm

From the first sight it's not clear at all what each version offers compared to the other ones, or even which Elixir version it supports.

I would also go as far as propose some mechanism to display the relevant changes for each version right on the site. @bitwalker has been doing a great job of keeping tags for all the releases of exrm, so it's at least possible to track commits between version. But take a look at inflex (https://hex.pm/packages/inflex) – it has 0 tags and no changelong. You'd basically need to traverse git history to find out what has changed between versions.

**Comment by ericmj** [comment]
Less important now that everything is on 1.0+. If we add this we would also need to add OTP requirement to be consistent which we don't do yet. It is also blocking on a requirements system as @josevalim mentioned.
