### ISSUE TITLE
Add audit log

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#202]
We need to add an audit log that tracks actions users perform on packages, users and package ownership.

Actions that need to be logged:

 * Release published/reverted
 * Documentation published/reverted
 * Package owner added/removed
 * API key generated/deleted
 * Password reset

Additionally we should consider not fully deleting packages, releases and docs - instead they can be flagged as deleted so they are kept for history. The same for tarballs but they should be made private when deleted. This strategy would still allow records to be overwritten when packages/docs are republished so it's not perfect.

**Comment by jcspencer** [comment]
Should this log be streamed to STDOUT, or should it be saved into a database or another separate logging service? 

On 5 January 2016 7:36:42 AM AEDT, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>We need to add an audit log that tracks actions users perform on
>packages, users and package ownership
>
>Actions that need to be logged:
>
> * Release published/reverted
> * Documentation published/reverted
> * Package owner added/removed
> * API key generated/deleted
> * Password reset
>
>Additionally we should consider not fully deleting packages, releases
>and docs - instead they can be flagged as deleted so they are kept for
>history The same for tarballs but they should be made private when
>deleted This strategy would still allow records to be overwritten when
>packages/docs are republished so it's not perfect
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/202

-- 
James Spencer

**Comment by ericmj** [comment]
It should be saved to the database.

On Tuesday, 5 January 2016, James Spencer <notifications@github.com> wrote:

> Should this log be streamed to STDOUT, or should it be saved into a
> database or another separate logging service?
>
> On 5 January 2016 7:36:42 AM AEDT, "Eric Meadows-Jönsson" <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >We need to add an audit log that tracks actions users perform on
> >packages, users and package ownership
> >
> >Actions that need to be logged:
> >
> > * Release published/reverted
> > * Documentation published/reverted
> > * Package owner added/removed
> > * API key generated/deleted
> > * Password reset
> >
> >Additionally we should consider not fully deleting packages, releases
> >and docs - instead they can be flagged as deleted so they are kept for
> >history The same for tarballs but they should be made private when
> >deleted This strategy would still allow records to be overwritten when
> >packages/docs are republished so it's not perfect
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >https://github.com/hexpm/hex_web/issues/202
>
> --
> James Spencer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/202#issuecomment-169001553>.
>


-- 
Eric Meadows-Jönsson

**Comment by wojtekmach** [comment]
Hi all, I'm not sure if you had a chance to discuss this feature in detail yet. If not, I'd like to take a stab at fleshing it out before implementing it. My proposal is mostly based on GitHub audit logs (https://help.github.com/articles/reviewing-your-security-log/).

**Base params**:

| Name             | Example value                    |
| ---------------- | -------------------------------- |
| `action`         | `"package.add_owner"`            |
| `actor`          | `"alice"`                        |
| `actor_ip`       | `"127.0.0.1"`                    |
| `inserted_at`    | `"2015-02-15 09:00:00"`          |

**Actions:**

- `owner.add`

| Name             | Example value                    |
| ---------------- | -------------------------------- |
| `package`        | `"foo"`                          |
| `user`           | `"bob"`                          |

- `owner.remove`
- `docs.publish`
- ...

**DB schema:**

```sql
CREATE TABLE audit_logs (
  id serial PRIMARY KEY,
  action text NOT NULL,
  actor text NOT NULL,
  actor_id integer REFERENCES users,
  actor_ip text NOT NULL,
  extra_params jsonb NOT NULL,
  created_at timestamp NOT NULL);
```

**Notes:**

- Would be good to disable UPDATE/DELETE operations on the audit_logs table for the web user. Not sure heroku postgres allows that though
- I decided to store both actor and actor_id, to both allow for fast lookup but also read the table without joins. I assume users.username is immutable so it should be safe to keep it denormalized
- Usage in controllers could be: `HexWeb.AuditLog.log(conn, action, extra_params)`
- Storing IPs in the audit log could be subject to data protection laws. I'm no expert in it, but perhaps at the very least we should ask for explicit consent before storing it? We could take IP collection out of the scope of this feature for now too.

This approach is pretty explicit which I think is good. An alternative approach would be to have something closer to e.g. https://github.com/collectiveidea/audited

What do you think?

**Comment by ericmj** [comment]
This looks like a great schema for the job.

> Would be good to disable UPDATE/DELETE operations on the audit_logs table for the web user. Not sure heroku postgres allows that though

I don't think heroku allows this since we only get one account.

> I decided to store both actor and actor_id, to both allow for fast lookup but also read the table without joins. I assume users.username is immutable so it should be safe to keep it denormalized

Fast lookup should not be necessary for this table so lets keep it normalized.

**Comment by wojtekmach** [comment]
@ericmj thanks for the feedback

> Fast lookup should not be necessary for this table so lets keep it normalized.

That's fine. Just so we're clear, do you prefer `actor` (string) or `actor_id` (foreign key) (and `package_id`, `release_id` for extra_params)? The former is gonna be easier to read when just browsing the table but the latter is gonna enforce DB integrity which is always good (albeit it would prevent manually removing referenced user which is probably fine too).

Another question is about capacity. Based on the current growth curve, do you foresee additional space constraints regarding this new table? There's always an option to periodically archive it.

**Comment by ericmj** [comment]
We should only store ids. We should never fully delete users, packages or releases so the references should be fine.

**Comment by ericmj** [comment]
Closing in favor of https://github.com/hexpm/hex_web/pull/238
