### ISSUE TITLE
Should not be possible to remove last owner of package

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#203]

**Comment by fteem** [comment]
May I? :)

**Comment by ericmj** [comment]
Go ahead

**Comment by msoedov** [comment]
@ferd Sorry it has been 6 days since your last post so I decided to make pr since there is no updates from your side.

**Comment by fteem** [comment]
@msoedov I guess you were referring to me. No problem, but next time, please ask before starting to work on it to avoid double effort.

**Comment by msoedov** [comment]
@fteem My bad, thanks :)

**Comment by wojtekmach** [comment]
@ericmj this can be closed :)
