### ISSUE TITLE
Allow for specification of language for a package

### ISSUE THREAD

**Issue by gmr** [hexpm/hex_web#204]
I think it'd improve usability if to have packages specify their primary language. If that data is stored, then the UI could then specify if it's an Erlang or elixir package and allow for filtering based upon such things. It would also allow for LFE and other beam languages to use hex without any confusion. For example, if I wanted to go pure Erlang for a particular type of package I am looking for, I should be able to filter out elixir packages.

Thoughts?

**Comment by ericmj** [comment]
We already have the build tool metadata which achieves this in a better way I think. Which language being used is not really that interesting, what's more interesting is if you can actually build and use the package. The build tool used is also a very strong hint on which language is used.

**Comment by ericmj** [comment]
Ping?
