### ISSUE TITLE
Find better way to validate metadata

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#205]
Currently the server side validation of metadata is basically non-existent so it almost always results in 500 errors or invalid data beings stored. We just need some rudimentary type validation on all metadata fields.

**Comment by wojtekmach** [comment]
Hey! Couple of notes:
- do we still need this issue open? There are already basic type validations on master e.g. here: https://github.com/hexpm/hex_web/blob/73bc8da4bf6e763d5416bfb81bfa247ed5f68ca3/web/models/package.ex#L34:L39
- have you considered using embeds to handle metadata? I was thinking about having explicit PackageMetadata and ReleaseMetadata models. I think it could work very well, in particular it would make things safer (`pkg.meta.maintainers` vs `pkg.meta["maintainers"]`), remove some boilerplate, and in general probably easier to maintain long-term. I have some early experimental branch of making that happen so I can definitely keep at it. So far I have only one blocker that  Ecto.Schema doesn't support field `{:dict, :string, :string} which we need for `pkg.meta.links` but that shouldn't be too hard to fix locally or perhaps eventually upstream in Ecto.

**Comment by ericmj** [comment]
Yeah, we still need it. The metadata validation we have today does not cover all cases and is kind of ugly. Using embeds is a nice way of cleaning it up, good idea. Please open an issue an ecto for `{:map, TYPE}` support, you can reference this issue. If ecto doesn't add it we can implement it ourselves.

Btw, requirements are also part of this and should be fixed in https://github.com/hexpm/hex_web/issues/257.

**Comment by wojtekmach** [comment]
@ericmj ok, sounds good. I created the issue on Ecto, and will start on doing embeds in the meantime.

**Comment by ericmj** [comment]
This was improved a lot with the move to ecto 2.0 but there are still things to clean up and more checks we can do so I am leaving it open.

**Comment by wojtekmach** [comment]
@ericmj do you have any particular validations in mind to add? I took a quick look at [PackageMetadata](https://github.com/hexpm/hex_web/blob/master/web/models/package_metadata.ex) and [ReleaseMetadata](https://github.com/hexpm/hex_web/blob/master/web/models/release_metadata.ex) and I think we could add the following:
- ensure `links` is a map of urls
- validate `elixir` with `Version.parse_requirement`

anything else?

**Comment by ericmj** [comment]
I think that's it. Your work on the metadata embeds and improvements to Requirement has got us 90% there.
