### ISSUE TITLE
Only display supported build tools in Config sidebar

### ISSUE THREAD

**Issue by tsloughter** [hexpm/hex_web#217]
It would be best if `rebar3` was not part of the Config sidebar version list when it is not a package with build tools that include rebar, rebar3 or make. rebar3 will currently filter out any other packages from the registry, which means a user who thinks from the website that they can use a package will find when trying to do so rebar3 complains it does not exist.

**Comment by ericmj** [comment]
So just to confirm; the rebar config should only be shown if the build tool is either rebar, rebar3 or make?

**Comment by tsloughter** [comment]
Correct.

**Comment by ericmj** [comment]
I would guess we should do the same for erlang.mk? /cc @elbrujohalcon

**Comment by elbrujohalcon** [comment]
@ericmj no, because erlang.mk can totally build rebar deps, no problemo.

**Comment by tsloughter** [comment]
@elbrujohalcon erlang.mk supports mix?

**Comment by elbrujohalcon** [comment]
@tsloughter good point. Unless @essen says otherwise, I would assume erlang.mk only knows how to build erlang.mk, make or rebar based projects.

**Comment by essen** [comment]
Erlang.mk supports anything with a Makefile, and rebar based project, by default. Plugins add support for LFE, Efene and Elixir projects, including Mix based. So if it's on Hex there's very little chance it won't build with Erlang.mk.
