### ISSUE TITLE
Improve config for erlang.mk

### ISSUE THREAD

**Issue by elbrujohalcon** [hexpm/hex_web#218]
Once ninenines/erlang.mk#497 is implemented, packages with names that differ from the app (e.g. https://hex.pm/packages/barrel_jiffy) will be allowed in erlang.mk with the format:

```make
dep_$(APP) = hex $(VERSION) $(PACKAGE)
```

**Comment by ericmj** [comment]
Closing this because it's not immediately actionable. Please send a PR when the feature is ready in erlang.mk.
