### ISSUE TITLE
Remove redirect docs GET request

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#220]
The endpoint "/api/packages/PACKAGE/releases/VERSION/docs" should be removed, it just redirects and the URL is available at "/api/packages/PACKAGE/releases/VERSION" anyway.

Also remember to remove from specification.

**Comment by mkaszubowski** [comment]
Hi, I'd like to work on this issue, just making sure: should I remove the entire endpoint or just the GET request?

**Comment by ericmj** [comment]
Just the redirecting GET request.
