### ISSUE TITLE
Fix sample data seed script

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#222]
The current seed script is not working.
File: `scripts/sample_data.exs`

**Comment by mkaszubowski** [comment]
@pragmaticivan Can you give more details? What kind of error is this? I tried running it on the most recent version and it works fine.

**Comment by pragmaticivan** [comment]
@mkaszubowski looks like it is fixed.

**Comment by pragmaticivan** [comment]
We can close this one.
