### ISSUE TITLE
404 Template page (bug)

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#223]
When you try to access the 404 behavior: `https://hex.pm/packages/xxxxxxx` the layout is being loaded twice.

**Comment by pragmaticivan** [comment]
I'm going to solve this in the new front-end PR.

**Comment by pragmaticivan** [comment]
I'm solving this one on #225

**Comment by ericmj** [comment]
Seems to be a phoenix issue https://github.com/phoenixframework/phoenix/issues/1504#issuecomment-180402720
