### ISSUE TITLE
copy_snippet function is not implemented

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#227]
![imagem](https://cldup.com/HP4h2Y8Fg0-3000x3000.png)

It's not implemented on this script, probably after phoenix migration.

Solving this problem with the new template as well.

**Comment by ericmj** [comment]
Actually all javascript seem to be broken, will need to fix this in master.

**Comment by ericmj** [comment]
All javascript is fixed except for ALL VERSIONS starting out expanded.

**Comment by ericmj** [comment]
All fixed now.
