### ISSUE TITLE
Hex Status Twitter Account

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#229]
What about creating a twitter account like https://twitter.com/rubygems_status ?

We can add a link in the new Front-end design.

**Comment by ericmj** [comment]
I think first we need an off-site status page and a way to actually automatically check the status of services.

**Comment by jcspencer** [comment]
This could be achieved with something like [statuspage.io](https://www.statuspage.io/) (unfortunately incredibly pricey at  $29/m, but alternatives exist), or simply running something like [Cachet](https://github.com/CachetHQ/Cachet) in another Heroku region or another region completely to ensure that even if Heroku itself goes down the status page will still be live

**Comment by ericmj** [comment]
Closing this for because it's low priority. If someone wants to work on it they are free to do so of course.
