### ISSUE TITLE
Docs archives no longer work

### ISSUE THREAD

**Issue by Kapeli** [hexpm/hex_web#232]
[Dash](https://kapeli.com/dash)'s integration with Hex relies on downloading the docs for packages. I used to be able to download the docs from URLs like https://hex.pm/api/packages/plug/releases/0.14.0/docs, but that doesn't work anymore.

Any idea what's going on? Did Hex stop supporting these archives?

**Comment by Kapeli** [comment]
As far as I can tell the archives are now located at URLs like https://s3.amazonaws.com/s3.hex.pm/docs/plug-0.14.0.tar.gz. Could redirects be added to support the old URLs too?

**Comment by ericmj** [comment]
You should use the new url instead or get the url from the HTTP API.

**Comment by Kapeli** [comment]
How do I get the URL using the HTTP API?

**Comment by ericmj** [comment]
The `docs_url` field at this endpoint: https://hex.pm/api/packages/plug/releases/0.14.0. Any reason you can't use the direct url? It should be more reliable.

**Comment by Kapeli** [comment]
I can use the direct url, but I was thinking maybe it would be best to use the API in case the URL will change again the future?

**Comment by ericmj** [comment]
The url has always been the same, the redirect was only removed.

**Comment by Kapeli** [comment]
Ah. I see. Any chance the redirect could be readded? :)

I can fix things from Dash's end, but it will take 7 days or so until Apple approves the update.

**Comment by ericmj** [comment]
I can temporarily add it back, but it would be great if you can fix it on your end also.

**Comment by Kapeli** [comment]
Great. Would it be ok if I'd fix it in the next release cycle which would be in 2-3 months? If not, I can cancel the current pending release and fix it in ~1 week.

**Comment by ericmj** [comment]
Deployed with the redirect added back. You can follow your planned release cycle, but please ping here when we can remove the redirect.

Just to satisfy my curiosity, is it a mac store app?

**Comment by Kapeli** [comment]
Thank you! I'll make sure to open an issue when it's safe to remove the redirect.

> Just to satisfy my curiosity, is it a mac store app?

Yep. It's also available outside of the App Store though.

**Comment by pfitz** [comment]
Thanks for working this problem so quickly out! Downloading docs with Dash is now working again! :+1:

**Comment by ericmj** [comment]
@Kapeli Has the new release gone out yet? We are planning to access the S3 bucket through Fastly CDN to improve performance and reduce our Amazon AWS costs so the URL is going to change. No worries if the release is already out, the direct S3 access is going to be available for quite a while.

**Comment by Kapeli** [comment]
The release is about 1 month away unfortunately.

Should I make a quick release that fixes this issue ASAP? The App Store review takes around 3 days, so I should be able to release in about 3-5 days.

**Comment by ericmj** [comment]
> Later edit: I just reread what you said and I think it's a good thing that the release isn't out yet as I should use the Fastly URLs instead?

Yes. We are currently in testing, I was just wondering if we needed to hurry up if you are releasing soon but now I know we have time to do some more testing. I will ping you in this issue again when we're ready to make it public.

**Comment by Kapeli** [comment]
Great. Thanks for the heads-up.

**Comment by ericmj** [comment]
@Kapeli The new endpoint is http://s3.hex.pm.global.prod.fastly.net

**Comment by Kapeli** [comment]
I'll make sure to use it in the next Dash version. I'll let you know when the update is live.

**Comment by ericmj** [comment]
Thank you :)

On Sun, Mar 13, 2016 at 6:32 PM, Bogdan Popescu <notifications@github.com>
wrote:

> I'll make sure to use it in the next Dash version. I'll let you know when
> the update is live.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/232#issuecomment-196008499>.
>



-- 
Eric Meadows-Jönsson

**Comment by Kapeli** [comment]
I've released the Dash update. Sorry for the wait!

If you can, please wait a week or so before removing the redirect, to give users time to update to the new version.
