### ISSUE TITLE
404 page shows a page within a page

### ISSUE THREAD

**Issue by henrik** [hexpm/hex_web#234]
https://hex.pm/packages/nosuchpackage

<img width="776" alt="screenshot 2016-02-10 22 34 51" src="https://cloud.githubusercontent.com/assets/216/12962619/831d845a-d046-11e5-9777-8be78d4082d7.png">

**Comment by pragmaticivan** [comment]
discussion here: #231

**Comment by henrik** [comment]
@pragmaticivan Thank you! Closing this one then.
