### ISSUE TITLE
Expose API over http too

### ISSUE THREAD

**Issue by gleber** [hexpm/hex_web#242]
Currently attempts to access API over http returns a 302 redirect to https endpoint:

```bash
$ curl -v http://hex.pm/api/packages/erlexec
* Hostname was NOT found in DNS cache
*   Trying 23.23.191.49...
* Connected to hex.pm (23.23.191.49) port 80 (#0)
> GET /api/packages/erlexec HTTP/1.1
> User-Agent: curl/7.38.0
> Host: hex.pm
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
* Server Cowboy is not blacklisted
< Server: Cowboy
< Date: Sun, 21 Feb 2016 01:20:41 GMT
< Content-Length: 0
< Cache-Control: max-age=0, private, must-revalidate
< Location: https://hex.pm/api/packages/erlexec
< Connection: keep-alive
< 
* Connection #0 to host hex.pm left intact
```

As far as I understand use of https prevents caching proxies. This is a problem for me, since I am scraping large chunk of hex.pm when developing `hex2nix` and importing metadata of some hex packages into http://github.com/nixos/nixpkgs

**Comment by ericmj** [comment]
It's very unlikely that we are going to allow HTTP access to the API. Many other APIs do the same, for example GitHub.

Why do you use a caching proxy when scraping?

**Comment by gleber** [comment]
It is handy while developing https://github.com/erlang-nix/hex2nix and iterating with various package metadata analysis approaches and various output generation approaches. I end up re-running it often enough to slow me down considerably. These requests are also rate-limited, since otherwise the scraping operation will be getting errors from the server. This tool already has caching layer, but it is happening after results of the API calls were processed as it was easier to put it there initially.

Given that the parts of API I am interested in are read only and globally accessible, the only reason to force https I see is to safeguard users of the API from tempering with data being transmitted to said users. Are there other?

To speed up development iterations, I've put a local caching http proxy for tarballs fetching, since they are available via http from S3. I wanted to use the same proxy to speed up API requests.

Looks like the workaround for me is to move the caching layer just after the API calls, so almost raw responses are cached before they are processed with any application logic.

**Comment by ericmj** [comment]
The future of the web is https, newer protocols doesn't even support http. There are many benefits for using https; security, SEO, etc. and it's much easier and safer to just force redirect all requests. If you rely on http you will have to change to https eventually anyway.

**Comment by gleber** [comment]
Agreed. Closing the issue.
