### ISSUE TITLE
Feature: Package Changelogs

### ISSUE THREAD

**Issue by connorshea** [hexpm/hex_web#248]
I've opened a similar issue before with Bundler, but [they weren't able to do this without RubyGems](https://github.com/bundler/bundler/issues/4243) supporting the feature. I've recently begun looking more into Elixir and Phoenix, so I figured I'd suggest this in the hopes that it could get in on the ground floor.

I'd love the option to have changes from the previous version to the current version of a Hex package be displayed in the Terminal after the dependency manager finishes updating.

My suggestion for Bundler was to make something that looks like this:

```
Connors-MacBook-Pro:Rails-Project connor$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Using rake 10.5.0
Installing stripe 1.34.0 (was 1.33.1)
Installing rails 4.2.5.1 (was 4.2.5)
Bundle updated!

CHANGES
-----------------------------
rails 4.2.5.1:
Fixes multiple important security vulnerabilities.

See http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/ for more information.

stripe 1.34.0:
Add support for deleting products and SKUs
```

I always have to check every gem's GitHub repository manually when a major version update comes out. It would be very nice to have Changelogs tracked by Hex so that Mix and co. can take advantage of the Changelogs in their CLIs.

Sorry about using the Bundler example, I'm still new to Elixir, so I didn't want to give a dumb example :P

If this isn't the correct place to suggest this feature, I will gladly suggest it elsewhere :)

Thanks, Connor

**Comment by ericmj** [comment]
While this would be a neat feature, I believe this is currently out of scope for the package manager. Hex is still in beta and we should focus on features that are core to package management.

An issue with this is that it's an extra step for package authors to do when publishing packages. As you may have noticed the configuration for a package is very thin and you only have to set it up once. With this feature instead of just running `mix hex.publish` you also have to set up the changelog every time you publish. I believe that every step should be very simple and quick when publishing otherwise people will just not bother with it.

**Comment by josevalim** [comment]
@ericmj I agree with you. However, I think it would be nice if we had a mechanism for showing messages after update. I think a CHANGELOG would be too much. It would just insane to show Ecto 2.0 CHANGELOG on upgrade but information like security releases would be likely welcoming. So I would call it like UPGRADE NOTICE or UPGRADE WARNING. It could be a simple file we place inside the Hex package.

**Comment by ericmj** [comment]
@josevalim That's something I have my wish list too. A way to tag releases with a message when publishing or even after they have been published would be nice. We could show the tags on hex.pm and when fetching the package.

Other useful messages would be for example deprecation messages telling people the package is no longer maintained and what they should use instead.

**Comment by ericmj** [comment]
The plan is to add a feature to add tags or messages to packages. It's not on the immediate roadmap so I am closing this issue. If anyone wants to work on the feature please open a new issue where it can be discussed in more detail.

**Comment by connorshea** [comment]
Works for me, thanks :)
