### ISSUE TITLE
Update to Ecto 2.0 beta

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#257]
1. Audit logs can be cleaned up by using `Ecto.Multi`
2. Requirement insertion and validation can be cleaned up by using `cast_assoc`
3. Creating package and package owner at the same time using either `Ecto.Multi` or `cast_assoc`
4. Resetting a user and all their keys can use either `Ecto.Multi` or `cast_assoc`
5. Clean up `HexWeb.Release.requirements/1` if the beta supports `%{model | ...}` select syntax

**Comment by wojtekmach** [comment]
@ericmj I'd like to tackle this; I'm not sure when I'm gonna be done but I should have some updates on it in a day or two

**Comment by ericmj** [comment]
Please go ahead, there is no rush :)

On Mon, Mar 7, 2016 at 10:24 PM, Wojtek Mach <notifications@github.com>
wrote:

> @ericmj <https://github.com/ericmj> I'd like to tackle this; I'm not sure
> when I'm gonna be done but I should have some updates on it in a day or two
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/257#issuecomment-193457503>.
>



-- 
Eric Meadows-Jönsson

**Comment by wojtekmach** [comment]
:) I guess what I was trying to say is it's probably gonna end up in multiple chunks of work (prob multiple commits) because looking at it, there's a lot of stuff this touches and so might make sense to review it in chunks potentially. But yeah, Multi rocks :)

**Comment by ericmj** [comment]
BTW, would be awesome if you include the traverse_errors change mentioned here https://github.com/elixir-lang/ecto/issues/1295#issuecomment-193681206.

**Comment by wojtekmach** [comment]
@ericmj yeah, I was thinking about it too. I don't think that change (improving validation messages) is necessarily related to ecto 2.0 upgrade, so it could be done off current master too I think.
