### ISSUE TITLE
Use HTTPS for hex.pm repository

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#268]
When we moved to Fastly we stopped using HTTPS for the repository. As part of Fastly's open source sponsorship they provide us with two CDNs for hexdocs and the hex.pm repository. They also provide us with a shared certificate that we use for https on hexdocs.

We no longer need HTTPS to verify the integrity of the registry and packages because we sign the registry and we keep checksums of packages in the registry. There is a privacy concern when not using HTTPS though, since the connection to the repository is not encrypted an attacker can find which packages you are using.

EDIT: For context https://twitter.com/lhoguin/status/711148433990619136

**Comment by ferd** [comment]
HTTPS will also be worthwhile when/If we get to handling cert revocation lists and so on, ensuring that at the very least, the list we get hasn't been manipulated by a MITM.

**Comment by ericmj** [comment]
> HTTPS will also be worthwhile when/If we get to handling cert revocation lists and so on, ensuring that at the very least, the list we get hasn't been manipulated by a MITM.

I was thinking we could solve that with an offline master key? There are also concerns with relying 100% on public key infrastructure.

**Comment by ferd** [comment]
I'm not sure how an offline master key would work there if the objective is to have tools able to go look at a revocation list online to know if the one they have is still good; if the access to the remote certs is MITM'd, no check is safe. You don't want to sign an empty CRL since you could just replay that over and over.

In fact that's an interesting problem with signing a package but not encrypting the communication and not including either some nonce or time-expiry technique in it: I am technically allowed to MITM things with a 3 year old version of the package index if I want to without problem, since the signature will be valid.

**Comment by ericmj** [comment]
> You don't want to sign an empty CRL since you could just replay that over and over.

You set an expire time on the CRL.

> You don't want to sign an empty CRL since you could just replay that over and over.

I am not sure providing an old registry is a security concern but we can add a creation time to the registry and have clients check that.

I don't think we can use nonce since we need to be able to serve this from CDNs. Any ideas?

**Comment by ferd** [comment]
The big common ways would probably be to sign the thing and include the signing time (a UTC epoch as a 64 bits integer with a well defined endianness for example) and a TTL that clients may choose to interpret with any level of tolerance. If the package served has been signed too long ago (or too far in the future), warn about it and consider it invalid.

**Comment by wub** [comment]
It's possible to, in the dashboard, add a domain with format `[anything-not-taken].global.ssl.fastly.net` - which is accessible globally, over both HTTP and HTTPS. Not sure if this fits with how they deal with free-CDN-for-FOSS, though.

**Comment by ericmj** [comment]
@wub Thanks, we have that setup now: https://github.com/hexpm/specifications/blob/master/endpoints.md. Hopefully we can get shared SAN certificate on fastly instead of using their shared wildcard certificate, I believe that should be more secure.

**Comment by wub** [comment]
@ericmj Thanks, next time I'll read before I post :-) I can see how proper certificates are important for this kind of thing.

**Comment by ericmj** [comment]
We have HTTPS for the repository again. Still looking into getting our domain for it while retaining HTTPS.
