### ISSUE TITLE
Make ownership clear in Terms of Service (also add Terms of Service)

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#269]
hex.pm does not own anything you publish but it will be made public and may be public forever. You may not have the ability to remove or change anything you have published.

**Comment by redvers** [comment]
Related: http://www.mail-archive.com/cpan-workers@perl.org/msg01430.html

Thread on cpan-workers on how they're addressing the same issue in a different way.  They separate code-ownership from namespace ownership.

Straight immutability still makes more sense in our ecosystem in my mind but adding the link for context.

**Comment by ericmj** [comment]
Closed in favour of #274.
