### ISSUE TITLE
Provide means of revoking registry certificate

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#273]
There is no current way to ensure the certificate has not been compromised with the current solution, and a PKI or equivalent seems like the only plausible, automated solution. 

From what I understand, for this to work effectively, you would need to use a pre-existing solution such as GPG where keys are publically accessible, immutable, and have the ability to be revoked.

**Comment by ericmj** [comment]
If the private key is compromised we will release new versions of the hex clients with a new public key, inform users on the website https://hex.pm/docs/public_keys and post it to mailing lists and other forums.

If we are going to add a more sophisticated signing process I would be happy to see it as a specification proposal.
