### ISSUE TITLE
Packages without releases behave inconsistently

### ISSUE THREAD

**Issue by enilsen16** [hexpm/hex_web#281]
Depending on the endpoint, inconsistent results are observed when a package has no releases. They appear in the index api endpoint as well as in the list of all packages on the site; however, if you try to view the "show" page for one, you get a 404. This does not happen with the api endpoint. Additionally, if you search for such a package using `mix hex.search`, you get no results; but if you try to register a package under the same, you wouldn't be able to.

**Comment by ericmj** [comment]
It's a long-standing bug that a package can exist with no releases. I believe it can happen in a few different ways but the most common one is when a package with only one release has that release reverted.
