### ISSUE TITLE
Enable notation of private packages in the specification

### ISSUE THREAD

**Issue by brucify** [hexpm/hex_web#283]
We are developing an app ([HexMirror](https://github.com/ieug/HexMirror/tree/develop_hex_mirror)) that enables you to mirror the package index so you can use your own [hex_web](https://github.com/hexpm/hex_web) to host your own private packages with alternative CDNs. 

The current [package metadata specification](https://github.com/hexpm/specifications/blob/master/package_metadata.md) have the following information. It would be good to add the notation of private packages into the spec.

- name (string)
- version (string)
- app (string) 
- description (string)
- files (list(string))
- licenses (list(string))
- contributors (list(string))
- links (kvlist(string => string))
- requirements (kvlist(string => kvlist(...)))
- app (string)
- optional (boolean)
- requirement (string)
- build_tools (list(string))

cc @yohaneskuma

Related issue: https://github.com/hexpm/hex_web/issues/164

**Comment by ericmj** [comment]
When running a package repository with private packages I don't packages should be mirrored from hex.pm. Instead hex clients (mix, rebar3, erlang.mk) should support pulling packages from multiple indexes.

Given that I would prefer to extend the specification to support cross-repository dependencies. A cross-repository dependency is when you depend on a package from another repository - that means your private package index can still depend on packages from hex.pm without mirroring.

Mirroring will still be useful because when you run a private repository it is likely that you don't want to depend on hex.pm as a source of failure.

**Comment by josevalim** [comment]
@ericmj Right, we need to support both. We should be able to say "I am a private package depending on this package from hex.pm" and we still need to be able to replace "hex.pm" by our own mirrors. Sometimes the private package AND the mirror are the same entity (which is @brucify's case).

**Comment by ericmj** [comment]
> We should be able to say "I am a private package depending on this package from hex.pm" and we still need to be able to replace "hex.pm" by our own mirrors. 

That's what I am suggesting.

> Sometimes the private package AND the mirror are the same entity (which is @brucify's case).

What's the use case for merging the mirror and private repository?

**Comment by josevalim** [comment]
> That's what I am suggesting.

I know, I was just clarifying/reinforcing. :)

> What's the use case for merging the mirror and private repository?

Well, if you have private packages and you don't want to depend on hex.pm, then you are doing both. No?

**Comment by ericmj** [comment]
> Well, if you have private packages and you don't want to depend on hex.pm, then you are doing both. No?

If the mirror repository is kept separate from the private repository I don't see the need for adding the notion of private packages to the metadata. Keeping them separate also has the benefit that you won't get conflicting package names between private and hex.pm packages.

If there's a use case for keeping the repositories together then I can see the need for adding it to the metadata. Or may be it can be useful anyway?

**Comment by ericmj** [comment]
@brucify @yohaneskuma Can you elaborate on what you need this for?

**Comment by ericmj** [comment]
Ping?

**Comment by ericmj** [comment]
Closing due to no feedback. Let us know if you have anything to add and we will reopen the issue and the discussion. Thank you!
