### ISSUE TITLE
The docs on hex.pm still mentions HEX_CDN

### ISSUE THREAD

**Issue by alco** [hexpm/hex_web#306]
See here https://hex.pm/docs/mirrors

However, when I run `HEX_CDN=https://s3.amazonaws.com/s3.hex.pm mix deps.get`, I get this warning:

> Hex.pm has moved to fastly and no longer uses the cdn configuration. To silence this warning you need to unset the environment variable HEX_CDN. If you would still like to use a mirror or custom repository, read the docs at:
>
>    mix help hex.config

Hex version 0.11.5

**Comment by ericmj** [comment]
Fixed on master.
