### ISSUE TITLE
Add favicon to browser search

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#307]

**Comment by jcspencer** [comment]
Add this to `hexsearch.xml`:

```xml
<Image height="48" width="48" type="image/x-icon">https://hex.pm/favicon.ico</Image>
<Image height="48" width="48" type="image/png">https://hex.pm/favicon.png</Image>
```

**Comment by ericmj** [comment]
I think it needs to be moved to a template if we are going to use `static_path` to get proper caching.

**Comment by jcspencer** [comment]
That's true. How long do clients (i.e. browsers) cache the OpenSearch file for?

**Comment by ericmj** [comment]
> That's true. How long do clients (i.e. browsers) cache the OpenSearch file?

I have no idea but it's convention in the rest of hex_web to use phoenix's static_path helper to create digested urls so I think it should be used here too to be consistent.
