### ISSUE TITLE
Broken link to github repo

### ISSUE THREAD

**Issue by jaimeiniesta** [hexpm/hex_web#310]
The link to the github repo in https://hex.pm/packages/elli_xpblfe contains a typo, a square bracket at the end:

https://github.com/quasiquoting/elli_xpblfe]

This is an invalid URL, apart from cleaning it up from the database contents maybe we could enforce the URL validation?

**Comment by ericmj** [comment]
I believe that's still a valid URL, although it links to a 404?

We should also avoid changing the metadata of packages in the database because it will still be the same in the package tarball. The package owner should fix it instead.

**Comment by jaimeiniesta** [comment]
I'm not sure about that, but the validator complains with:

https://validator.nu/?doc=https%3A%2F%2Fhex.pm%2Fpackages%2Felli_xpblfe

I think that the square bracket should have been [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding).

Anyway, what's important here is the 404. I'll ping the owner of the package, closing here as it's not a hex_web issue.

**Comment by ericmj** [comment]
Unfortunately I don't know how to validate it, `URI.parse/1` seems to accept it.

**Comment by jaimeiniesta** [comment]
Also, `URI.encode/1` doesn't transform the `]` into `%5D` as I had expected.

**Comment by yurrriq** [comment]
Thanks for the heads up and PR. It might be good to do some client-side validating in the tooling.
