### ISSUE TITLE
Disabled fonts may show unexpected results

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex_web#312]
I am not sure if we can do something about this. Many mobile users will have disabled things like custom fonts as they are common in adblockers and similar tools. When such happens, the website uses non-ideal icons, look at the kiss sign near to the search in the screenshot below). I am not sure if this could be fixed but I thought I would report it anyway.

![img_3709](https://cloud.githubusercontent.com/assets/9582/14645552/693c4b7a-0656-11e6-9672-ae27c77e200f.jpg)

**Comment by pragmaticivan** [comment]
Never experienced anything like that I just use AdBlocker in my desktop. Have no idea how would we solve that, because Even if we have a fallback this `kiss` will be above the fallback layer.

**Comment by ericmj** [comment]
We should also reduce the size of fonts or at least the number of fonts used on the website. People have reported bad user experiences on slow networks. There have also been issues where no text was showing on the page when fonts failed to load.

**Comment by pragmaticivan** [comment]
@ericmj those are the fonts we're using 
```
@import "lato";
@import "octicons";
```
Not sure how can we reduce that they're also using google CDN.

**Comment by pragmaticivan** [comment]
@ericmj ^

**Comment by ericmj** [comment]
@pragmaticivan We have the option of reducing the number of fonts we use. We use at least 4 or 5 different font weights of lato, each requiring separate HTTP requests to fetch them. We can also use a different font than lato that has smaller file sizes.

Neither option seems great.

**Comment by ericmj** [comment]
We can inline the icons we use (glyphicons and octicons) instead of using icons fonts like outlined in this GitHub blog post: https://github.com/blog/2112-delivering-octicons-with-svg.

It will require some extra work because we need to parse XML and/or CSS files to get the icon SVG data, but it's definitely doable.

**Comment by ericmj** [comment]
Icon fonts are now inline SVG: https://github.com/hexpm/hex_web/pull/354

**Comment by ericmj** [comment]
The initial bug in this issue is fixed. We should still try to reduce the number of actual fonts we are using but that's not directly actionable right now since we don't have a solution for it so I am closing this for now.
