### ISSUE TITLE
Left-side navigation menu is broken on small screens (mobile)

### ISSUE THREAD

**Issue by austinsmorris** [hexpm/hex_web#321]
If your screen is small enough (small on desktop, always on mobile), the left side menu will not stay open.  If you click the hamburger to expand the menu, it slides out and disappears, making it unusable.

**Comment by pragmaticivan** [comment]
@austinsmorris can you add more info? which device have you used for this test? what's the screen size? In my for example is working very well (Nexus 6P and iPhone 6)

**Comment by austinsmorris** [comment]
For me, it appears to be any screen width below 768px.

This happens on my iPhone 6s with safari and chrome (all latest versions).  It also happens on my desktop any time I shrink width below 768px (chrome, safari, and firefox).

**Comment by ericmj** [comment]
I can't reproduce either. It works for me on iPhone 6S and the different viewport sizes for mobile devices in chrome.

**Comment by ferd** [comment]
I get a way cooler effect when I shrink the window size

![](http://i.imgur.com/7Lxsi6C.png)

**Comment by ericmj** [comment]
@fred Issue open here https://github.com/hexpm/hex_web/issues/316

**Comment by austinsmorris** [comment]
Ok, it must have something to do with content.  Ecto docs work for me, but check out:

https://hexdocs.pm/absinthe/Absinthe.html
https://hexdocs.pm/absinthe_relay/Absinthe.Relay.html

**Comment by wojtekmach** [comment]
@austinsmorris based on two links above, seems like you might be experiencing design issues with hexdocs.pm, and not hex.pm itself. Even though hex_web helps with hosting the docs, the docs generation, layouts, styles etc happens elsewhere. See: https://github.com/elixir-lang/ex_doc. Perhaps open issue there?
