### ISSUE TITLE
Description limit for package page

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#326]
Check this example: https://hex.pm/packages/timex

**Comment by ericmj** [comment]
Please open an issue with timex also. The description is supposed to be a few paragraphs at most.

**Comment by pragmaticivan** [comment]
Just sent a PR for timex, we can close this one, they'll update in the next release.

**Comment by ericmj** [comment]
Maybe we should cap the description at a number of characters also? Either only when displaying or also as a validation when publishing.

**Comment by pragmaticivan** [comment]
For that you need to go into the db and check what's the biggest description and make it the default description size limit. Or at least have a way to improve the description of old packages.

**Comment by ericmj** [comment]
We don't have to change old packages or be limited by them when adding a validation.

**Comment by pragmaticivan** [comment]
Cool, so, characters enough for 2 lines?

**Comment by ericmj** [comment]
Yeah, I think that would be okay. Maybe double the size of a tweet, ~300 characters?

**Comment by pragmaticivan** [comment]
Should we close this one since it's merged as a warning alert?

**Comment by ericmj** [comment]
We need to limit the description size on the package page also.
