### ISSUE TITLE
Page rendering issues for packages with long names

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/hex_web#329]
there is a base line rendering issue which cuts off the bottom of letters for packages with longer names when the view is scaled for mobile.

https://hex.pm/packages?_utf8=%E2%9C%93&search=nerves_toolchain&sort=downloads

In addition, On the package page, there is an issue with where the version is placed when the package name takes up the whole line.

https://hex.pm/packages/nerves_toolchain_arm_unknown_linux_gnueabihf

**Comment by pragmaticivan** [comment]
cc @ericmj what do you think about this case? Should I overflow wich CSS like the last PR I sent?

**Comment by jcspencer** [comment]
I think most of these issues can be fixed by doing the following:

- don't enforce the same line-height on all platforms
- use the bootstrap grid system
- wrap long text inside it's parent

**Comment by ericmj** [comment]
@pragmaticivan Yes, please do.

**Comment by pragmaticivan** [comment]
I created a solution for that and looked good because we don't hide the real name of the package and also works with the mobile version.

<img width="1157" alt="screen shot 2016-05-21 at 12 43 43 pm" src="https://cloud.githubusercontent.com/assets/301291/15449931/b099740c-1f51-11e6-98e0-c26822db0bd6.png">

**Comment by pragmaticivan** [comment]
<img width="387" alt="screen shot 2016-05-21 at 12 44 41 pm" src="https://cloud.githubusercontent.com/assets/301291/15449936/fc875b9a-1f51-11e6-80b6-9c8ed8adc69b.png">
