### ISSUE TITLE
Add a filter to be able to search for only Erlang or only Elixir packages

### ISSUE THREAD

**Issue by aberman** [hexpm/hex_web#333]
It would be very helpful if the hex.pm website allowed a filter to only show Erlang or Elixir or both.  There are many times that I do a search or I browse and only want to see, for example, Erlang packages.

**Comment by ericmj** [comment]
The language(s) used by a package is not stored in the package metadata, we only store the build tool used to build the project and that is not a great indicator of what languages are used in the package.

**Comment by aberman** [comment]
I think that's a fair indicator though.  If I'm programming in Erlang, chances are I'm not using mix, but rebar3 and vice versa for Elixir projects.  Given that that is what is stored in the metadata, it would still be helpful to filter based on the build tool used.

**Comment by ericmj** [comment]
Most Elixir programmers use Erlang libraries though. I am aware that Erlang applications do not depend on Elixir apps due to it being difficult but the plan is to add support in Rebar3 (or with a plugin) for compiling Elixir projects so I think this will be even less useful in the future.

**Comment by aberman** [comment]
Ah, ok, if that's the case, then you're right, it won't be useful.

**Comment by vassilevsky** [comment]
Hello 🙃 I came here to create such an issue. Would be cool to see which packages are for Erlang only. What are the developments in cross-language interoperability now (since this issue was closed)? Sorry, I'm fairly new in BEAM-land 😅

**Comment by ericmj** [comment]
You can use erlang libraries from elixir and vice versa if you use rebar3 [1].

[1] https://github.com/tsloughter/rebar_mix
