### ISSUE TITLE
Package name text is cut off at bottom

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#334]
<img width="319" alt="screen shot 2016-05-11 at 16 06 34" src="https://cloud.githubusercontent.com/assets/316890/15183681/6f9c5a62-1792-11e6-835a-7731513e5fd2.png">

The bottom of "g" in "Plug" is cut off.

**Comment by optikfluffel** [comment]
It seems [web/static/css/template/_home.scss#L266](https://github.com/hexpm/hex_web/blob/3a0ae074c2b3555b363597f7af36d08f7e6c68df/web/static/css/template/_home.scss#L266) is the culprit.
I'm not really sure why `display: block;` is there, doesn't break anything at first sight (using Safari).
