### ISSUE TITLE
Release API Returns DateTime without Timezone

### ISSUE THREAD

**Issue by blatyo** [hexpm/hex_web#340]
The release API returns DateTime strings that are not valid because they're missing the timezone. Oddly, the package API returns DateTime strings that do have timezone information. This becomes an issue when trying to parse it. 

`2016-04-29T15:24:41.275558` was the `inserted_at` for https://hex.pm/api/packages/phoenix/releases/1.2.0-rc.0

Below see the issue with parsing and then it working when adding the timezone (Z at the end).
```
iex(18)> s = "2016-04-29T15:24:41.275558"
"2016-04-29T15:24:41.275558"
iex(19)> Timex.parse!(s, "{ISO}")
** (Timex.Parse.ParseError) Expected at least one parser to succeed at line 1, column 26.
    (timex) lib/parse/datetime/parser.ex:87: Timex.Parse.DateTime.Parser.parse!/3
iex(19)> s = "2016-04-29T15:24:41.275558Z"
"2016-04-29T15:24:41.275558Z"
iex(20)> Timex.parse!(s, "{ISO}")
#<DateTime(2016-04-29T15:24:41Z)>
```

**Comment by ericmj** [comment]
To me it looks like none of them have timezone information.

@josevalim Do I need to use a custom DateTime type if I want it to JSON encode with "Z" at the end?

**Comment by blatyo** [comment]
@ericmj Looks like this might be a regression. I have an exvcr recorded response for https://hex.pm/api/packages/abnf and it has timezone information, however requesting it now, it doesn't. Makes me feel a bit better, because I couldn't figure out why they were different either.

I'll take a swing at fixing this if you don't beat me to it.

Recorded response:
``` json
[
  {
    "request": {
      "body": "",
      "headers": [],
      "method": "get",
      "options": [],
      "request_body": "",
      "url": "https://hex.pm/api/packages/abnf/"
    },
    "response": {
      "body": "{\"url\":\"https://hex.pm/packages/abnf\",\"updated_at\":\"2015-11-16T01:33:40.914462Z\",\"releases\":[{\"version\":\"0.0.1\",\"url\":\"https://hex.pm/api/packages/abnf/releases/0.0.1\",\"updated_at\":\"2015-11-16T01:33:40.927884Z\",\"inserted_at\":\"2015-11-16T01:33:40.927876Z\"}],\"name\":\"abnf\",\"meta\":{\"maintainers\":null,\"links\":{\"GitHub\":\"https://github.com/vanstee/abnf\"},\"licenses\":[\"MIT\"],\"description\":\"ABNF parser for Elixir\",\"contributors\":null},\"inserted_at\":\"2015-11-16T01:33:40.914455Z\",\"downloads\":{\"all\":20}}",
      "headers": {
        "Connection": "keep-alive",
        "Server": "Cowboy",
        "Date": "Sat, 14 May 2016 16:59:15 GMT",
        "Content-Length": "497",
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "public, max-age=60",
        "Strict-Transport-Security": "max-age=31536000",
        "X-Ratelimit-Limit": "100",
        "X-Ratelimit-Remaining": "98",
        "X-Ratelimit-Reset": "1463245216",
        "Etag": "48495b5d0ecf4a4cce3b57db0754f117",
        "Last-Modified": "Mon, 16 Nov 2015 01:33:40 GMT",
        "Vary": "accept, accept-encoding",
        "Via": "1.1 vegur"
      },
      "status_code": 200,
      "type": "ok"
    }
  }
]
```

**Comment by ericmj** [comment]
It is indeed a regression but I don't know how to best fix it or even if we should fix it and update the specification instead.

**Comment by blatyo** [comment]
This appears to be the change that caused the issue: https://github.com/elixir-lang/ecto/commit/5d1902588ca771cb6e96487375133e904c68daf0

I'm going to follow up there.

My 2 cents are that dates should follow an existing specification. The dates as they are now, almost follow ISO 8601 and used to. It is also one of the more readable formats and [supported by ecto](https://hexdocs.pm/ecto/2.0.0-rc.5/Ecto.DateTime.html#to_iso8601/1).

Interestingly, I found this blog post while trying to debug the issue: http://blog.plataformatec.com.br/2014/11/how-to-serialize-date-and-datetime-without-losing-information/

**Comment by ericmj** [comment]
Ecto does follow the specification, time zone information is not required in ISO 8601. And ecto does serialize to ISO 8601 with as much information as it has, ecto doesn't know the time zone so it shouldn't print a time zone.

In this case the application knows the time zone so we should try to print it, but I don't know the best approach yet.

**Comment by josevalim** [comment]
@ericmj doesn't the Hex client always send UTC? So you know that the datetime is UTC but Ecto does not know it. I know software like Calecto solves it by allowing you to specify something like DateTimeUTC so it would include the Z at the end and that's a choice you could make.

Other than that, our datetime does follow the ISO8601 standard.

**Comment by ericmj** [comment]
@blatyo If you would like to work on this we have two alternative solutions; either use Calecto or add a custom datetime ecto type that prints with a "Z" and falls back to Ecto.DateTime. I vote for the latter alternative, adding a dependency to print Zs seems like too much.

**Comment by blatyo** [comment]
Yea, I'll take a look tonight.

**Comment by josevalim** [comment]
Because this is using the JSON encoder, it means you do not only need a custom Ecto type, you also need a custom struct. I would hold until Elixir v1.3 which will supposedly make this is easier.

**Comment by ericmj** [comment]
Unfortunately we are breaking API clients, so we need a workaround.

**Comment by josevalim** [comment]
Try reimplementing the Poison.Encoder protocol for Ecto.DateTime. It will emit warnings when you do so though.

**Comment by blatyo** [comment]
Ah, missed the latter part of this conversation. I'll try the Poison.Encoder protocol route.

**Comment by enilsen16** [comment]
This regression seems to be back again, however I am seeing it in both APIs now...

**Comment by blatyo** [comment]
Yea, seeing it again as well. Not sure what caused it.
