### ISSUE TITLE
Release API Returns DateTime without Timezone

### ISSUE THREAD

**Issue by blatyo** [hexpm/hex_web#356]
The API has regressed again and stopped returning Timezone information for DateTimes. See this URL for example:

https://hex.pm/api/packages

Happy to fix this, but not sure where to look. #343 fixed this before, but seems to have stopped working. The previous ticket discussing the issue was #340.

Thanks

**Comment by blatyo** [comment]
Thanks!

**Comment by enilsen16** [comment]
Thanks @ericmj!
