### ISSUE TITLE
Allow using email everywhere that accepts usernames

### ISSUE THREAD

**Issue by fishcakez** [hexpm/hex_web#358]
It is more convenient to use an email address, rather than a username, for example when generating an API key.

**Comment by ericmj** [comment]
We also need to update the HTTP API specification after this change.

We should also look into if we can fully deprecate usernames in favor of only using email address as account id.

**Comment by fteem** [comment]
@ericmj @fishcakez I'd like to give this a shot. Should we drop support of usernames completely, or do we just extend the functionality with email support?

**Comment by ericmj** [comment]
@fteem We should only extend it to email support. I think it would be too disruptive to drop usernames completely.

**Comment by ericmj** [comment]
Let us know if you find any other places where the email does not work in place of the username.
