### ISSUE TITLE
Do not overflow package names on front page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#370]
<img width="568" alt="screen shot 2016-06-22 at 18 26 22" src="https://cloud.githubusercontent.com/assets/316890/16274841/a05eb57e-38a7-11e6-98e7-d26a83db6c81.png">

**Comment by josevalim** [comment]
I am stealing @fishcakez's joke here and saying that nerves packages soon will hit the 255 character limit for package names. :P

**Comment by fishcakez** [comment]
@josevalim you need to work on the delivery :stuck_out_tongue:

**Comment by josevalim** [comment]
📦

**Comment by jbranchaud** [comment]
@ericmj I'm willing to work on this bug. Is there a particular approach you have in mind for addressing this or should I just propose something in a PR?

**Comment by ericmj** [comment]
I think we should handle the overflow by replacing it with an ellipsis.

On Thu, Jun 30, 2016 at 6:32 PM, Josh Branchaud <notifications@github.com>
wrote:

> @ericmj <https://github.com/ericmj> I'm willing to work on this bug. Is
> there a particular approach you have in mind for addressing this or should
> I just propose something in a PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hexpm/hex_web/issues/370#issuecomment-229713964>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATV2skWcylZCGDaAszEDYIzEHoKfuBrks5qQ--YgaJpZM4I7-g6>
> .
>



-- 
Eric Meadows-Jönsson
