### ISSUE TITLE
Fastly redirecting to https, which doesn't have a valid certificate

### ISSUE THREAD

**Issue by Kapeli** [hexpm/hex_web#371]
http://s3.hex.pm.global.prod.fastly.net/ redirects to https which fails because it doesn't have a valid certificate. This causes the [Dash](https://kapeli.com/dash) integration to fail.

```
wget http://s3.hex.pm.global.prod.fastly.net/docs/phoenix-1.2.0.tar.gz
--2016-06-30 02:56:36--  http://s3.hex.pm.global.prod.fastly.net/docs/phoenix-1.2.0.tar.gz
Resolving s3.hex.pm.global.prod.fastly.net (s3.hex.pm.global.prod.fastly.net)... 185.31.18.249, 185.31.19.249
Connecting to s3.hex.pm.global.prod.fastly.net (s3.hex.pm.global.prod.fastly.net)|185.31.18.249|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.hex.pm/docs/phoenix-1.2.0.tar.gz [following]
--2016-06-30 02:56:37--  https://s3.hex.pm/docs/phoenix-1.2.0.tar.gz
Resolving s3.hex.pm (s3.hex.pm)... 54.231.120.3
Connecting to s3.hex.pm (s3.hex.pm)|54.231.120.3|:443... connected.
The certificate's owner does not match hostname ‘s3.hex.pm’
```

// @ericmj

**Comment by ericmj** [comment]
Thanks for the report it should be fixed now, it was a misconfiguration on our CDN.

If you want to use https use `https://repo.hex.pm/...`. I know I said we wouldn't be changing CDN urls (so that's kind of embarrassing :flushed:), but if you could switch over that would be great. There's no hurry of course.

**Comment by Kapeli** [comment]
Thanks for the extremely quick fix. All working now.

I'll switch to `https://repo.hex.pm/` in the next Dash update.

**Comment by josevalim** [comment]
@Kapeli  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
