### ISSUE TITLE
feature request: expose direct download link of packages

### ISSUE THREAD

**Issue by c0b** [hexpm/hex_web#379]
see https://groups.google.com/d/msg/elixir-lang-talk/nm3GaX_tdLw/4pTSWktNCgAJ for background

> I think hex.pm is an equivalent to python community's pypi index, however 

> https://pypi.python.org/pypi/ipython from this page I can use browser download the source code in a tarball or other format 

> https://hex.pm/packages/httpotion from this page, if without mix tool how do I download source code ? 

Then any developer behind hex.pm can comment here? Why designed this service not allowing people directly download from web ? someone might say the github for httpotion is exposed you can download from github for tarball, I'm not sure is that true for all hex.pm packages ? and 
for all historical versions like https://hex.pm/packages/httpotion/2.2.2 is there always a github 
release for that? what if the original github user has deleted his repo?

Another advice is the web page https://hex.pm/packages/httpotion looks too simple and not good for Search Engine SEO, some developer here could at least populate the README from upstream packages ?

and some simple review feedback system would be also good, a good practice or headache from other language communities is when there are multiple choices for same functionality it's hard for user to tell which one has better code quality or maturity, then user has to research a lot on Google

https://github.com/myfreeweb/httpotion has 446 stars could be a good indication ; I would like to see https://hex.pm/packages/httpotion to show the README and number of stars

**Comment by josevalim** [comment]
Can we please keep the issues focused? This one has at least two
discussions: packages downloads and SEO. Those should be separate issues
specially because I don't think we should be fetching information from
GitHub and instead keep it simple since Hex is about the package itself and
not any sort of aggregator.

On Friday, July 8, 2016, Mr C0B <notifications@github.com> wrote:

> see
> https://groups.google.com/d/msg/elixir-lang-talk/nm3GaX_tdLw/4pTSWktNCgAJ
> for background
>
> I think hex.pm is an equivalent to python community's pypi index, however
>
> https://pypi.python.org/pypi/ipython from this page I can use browser
> download the source code in a tarball or other format
>
> https://hex.pm/packages/httpotion from this page, if without mix tool how
> do I download source code ?
>
> Then any developer behind hex.pm can comment here? Why designed this
> service not allowing people directly download from web ? someone might say
> the github for httpotion is exposed you can download from github for
> tarball, I'm not sure is that true for all hex.pm packages ? and
> for all historical versions like https://hex.pm/packages/httpotion/2.2.2
> is there always a github
> release for that? what if the original github user has deleted his repo?
>
> Another advice is the web page https://hex.pm/packages/httpotion looks
> too simple and not good for Search Engine SEO, some developer here could at
> least populate the README from upstream packages ?
>
> and some simple review feedback system would be also good, a good practice
> or headache from other language communities is when there are multiple
> choices for same functionality it's hard for user to tell which one has
> better code quality or maturity, then user has to research a lot on Google
>
> https://github.com/myfreeweb/httpotion has 446 stars could be a good
> indication ; I would like to see https://hex.pm/packages/httpotion to
> show the README and number of stars
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hexpm/hex_web/issues/379>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbnZP_g_jpm3SclwWMg8jcJbTF8rJks5qToJHgaJpZM4JINp9>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
> Then any developer behind hex.pm can comment here? Why designed this service not allowing people directly download from web ? someone might say the github for httpotion is exposed you can download from github for tarball, I'm not sure is that true for all hex.pm packages ? and 
for all historical versions like https://hex.pm/packages/httpotion/2.2.2 is there always a github 
release for that? what if the original github user has deleted his repo?

We can add a direct download link of the tarball from the package page on hex.pm. What's the use case for downloading packages outside of mix/rebar?

> Another advice is the web page https://hex.pm/packages/httpotion looks too simple and not good for Search Engine SEO, some developer here could at least populate the README from upstream packages ?

This has been discussed before. We currently cannot support this because we don't have markdown (or other) engines that correctly handles cross-site scripting (XSS).

> and some simple review feedback system would be also good, a good practice or headache from other language communities is when there are multiple choices for same functionality it's hard for user to tell which one has better code quality or maturity, then user has to research a lot on Google

This can be achieved by external services that fetch data from Hex's HTTP API. We think it's important to keep Hex focused on core package manager functionality.

**Comment by josevalim** [comment]
> We can add a direct download link of the tarball from the package page on hex.pm. What's the use case for downloading packages outside of mix/rebar?

It would be nice to have a mechanism that allows us to download and check the package source without forcing us to create a project and add it as a dependency.

**Comment by ericmj** [comment]
Please send a PR if you are interested in this feature.
