### ISSUE TITLE
Wired bars in the package list

### ISSUE THREAD

**Issue by michalmuskala** [hexpm/hex_web#384]
I noticed this yesterday but it is still present so I decided to report.

Google Chrome Version 51.0.2704.103 (64-bit)
OS X 10.11.5

<img width="322" alt="screenshot 2016-07-14 16 36 16" src="https://cloud.githubusercontent.com/assets/477062/16843361/4297b2f6-49e1-11e6-9f52-0ba210399797.png">

**Comment by ericmj** [comment]
I can't reproduce on Chrome and OS X. If someone has the same issue and know a fix please send a PR.
