### ISSUE TITLE
How can we report deprecated packages? 

### ISSUE THREAD

**Issue by fladson** [hexpm/hex_web#394]
I'm maintaining the awesome-elixir list and I've found some hex links that points out to non existent gh repos, so I'm assuming they are deprecated. 

There is any way to report them or we shouldn't remove them?

Thanks for the awesome work!

**Comment by ericmj** [comment]
We are adding package yanking, keep a look at this PR https://github.com/hexpm/specifications/pull/10. When you yank a package you can give a message such as a notice that the package is deprecated.

Only the owner will be able to do this though. You won't be able to deprecate others' packages.

**Comment by fladson** [comment]
I see, thanks for the response.
