### ISSUE TITLE
Improve stats job to be more memory efficient

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#398]
Currently when running the stats job locally when memory is restricted, the stats job crashes with large (200k lines) amounts of simulated log data.

**Comment by ericmj** [comment]
Why do you have 200k lines of test logs? Can you elaborate on the log data you have and how memory there is on the machine where it's crashing. Memory usage from the observer app could also be useful.

After this commit https://github.com/hexpm/hex_web/commit/e8aca5a50292c80788ec7c9febe73dc21dad7b8e it's currently working with production access logs from S3 and Fastly when running the job on heroku (512mb memory). After gen_stage is out and ex_aws is using it we can further improve the memory usage.

Do you have any ideas on how to improve the memory usage? I don't think we should have issues that are not directly actionable.

**Comment by jcspencer** [comment]
I have just realised I was running these tests against a tree prior to the commit e8aca5a. I used a basic script to generate 200k lines of Fastly logs to simulate daily log traffic.
