### ISSUE TITLE
Add support for tracking security issues in hex packages. 

### ISSUE THREAD

**Issue by idyll** [hexpm/hex_web#400]
Since pulling a package is not supported I think it is important to understand security issues reported against versions of packages. 

This is more than just there's a new version but should define a level (low, medium, high) of risk and notes that include upgrade advice and/or mitigation strategy. 

Ideally it could be integrated into hex or another tool and trigger build warnings or failures.

**Comment by idyll** [comment]
@ericmj this is maybe a better place to discuss.

**Comment by ericmj** [comment]
We are add package yanking, take a look at https://github.com/hexpm/specifications/pull/10. It seems like what you are proposing but it won't have low/med/high levels.

**Comment by idyll** [comment]
Yeah that should cover it. I will close this issue but perhaps `deprecate` or `retire` or `renounce`  would be a better name for yank.
