### ISSUE TITLE
Add canonical link to current version 

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [hexpm/hex_web#409]
I keep running into the problem that google sends me to old versions of documentation. As one example, a search for [phoenix presence] currently returns the result shown below, although version 1.2.0 is available.

HexDocs can be configured to include a ref="canonical" link to the current version as I found in https://github.com/elixir-lang/ex_doc/pull/517. Sorry for not sending a pull request, but I couldn't quite figure out where this would be implemented.

![screen shot 2016-09-23 at 01 50 09](https://cloud.githubusercontent.com/assets/10232033/18769741/1bc049b4-8130-11e6-839a-0a0982d023c9.png)

**Comment by josevalim** [comment]
Hi, you need to do so in your docs generation configuration. You can do:

    docs: [canonical: "https://hexdocs.com/PACKAGE"]

So i think what we need to do here is send pull requests to existing
projects to include canonical and improve our documentation to include
canonical as well.


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
@wojtekmach added support for setting `:canonical` to hexdocs by default. Unfortunately Phoenix 1.2.0-rc.0 was published before this default was added and we can't change the html for already published documentation.

I will look into if there's an easy way we can set a `Link: <https://hexdocs.pm/phoenix/Phoenix.html>; rel="canonical"` header.

**Comment by ericmj** [comment]
We are now setting the Link header with Fastly (our CDN). Please check it out and if see if the header looks correct on different hexdocs.pm pages.

**Comment by ericmj** [comment]
Closing this since no issues has been reported regarding the new canonical Link headers. Please let me know if you find anything.

**Comment by ericmj** [comment]
Seems like Google is respecting the new headers:

![screen shot 2016-10-10 at 16 27 21](https://cloud.githubusercontent.com/assets/316890/19239468/7e0d8562-8f06-11e6-8d01-44e53c41377c.png)

**Comment by MatthiasWinkelmann** [comment]
Indeed! Thank's for your work – I'm sure there'll be thousands of people going home a tiny bit happier (and maybe earlier) over the next decade without ever knowing why :)
