### ISSUE TITLE
Fragment links for task docs scroll too far

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#414]
The header hides part of the documentation when following fragment links on: https://hex.pm/docs/tasks

**Comment by TakteS** [comment]
@ericmj Hello. You about this?
![out](https://cloud.githubusercontent.com/assets/7054944/19012506/28b6dd5a-87fb-11e6-8eaa-8f371daf364b.gif)

**Comment by ericmj** [comment]
That looks perfect. Could you send a PR for that?

**Comment by TakteS** [comment]
@ericmj #419  I'm sorry for the delay ;)

**Comment by wojtekmach** [comment]
Thanks again @TakteS!
