### ISSUE TITLE
Future: Move registry to log structured format or similar structure

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#42]
This is a change that would be both 100% backwards *incompatible* and would require a fair amount of work, but as the size of the registry continues to grow, it is something we need to, at the very least, consider. This is a discussion for the future, and is definitely not something we will be able to implement for a while yet!

Currently, whenever the registry is updated, users need to download the entire file again, which at the moment is perfectly fine, but as the registry file size grows, this is an unrequired step, and could potentially use a fair amount of unwanted bandwidth if packages are installed often.

My proposal is to format the registry in a different way than the current ETS table. The option I've looked at is moving the registry to a log structured key-value hashtable. One example implementation is [spotify/sparkey](https://github.com/spotify/sparkey).  It is basically a log and an index that is appended to with `PUT` or `DELETE` operations,  and any data already in the file is completely immutable and append-only, allowing us to grab all the changes since we last downloaded it (the bytes after the last byte we have downloaded).

Another positive is of using sparkey is that *any* amount of concurrent independent readers can be used, but it only allows one writer at a time per storage unit, whilst allowing a high throughput when performing bulk writes.

Sparkey also allows Google Snappy compression, letting you select a block size which is then used to split the contents of the log into blocks. Each block is compressed independently with snappy.

As I stated earlier, this is a change that would be both 100% backwards *incompatible* and would require a fair amount of work, but this will dramatically cut down on unrequired bandwidth usage and allow for quicker pulling of the registry, as well as making Hex snappier for clients.

>Note: This aimed to be more of a discussion starter than a full-blown proposal, and feedback would be appreciated!

**Comment by tsloughter** [comment]
Just to throw in my 2 cents since rebar3 plans to use Hex :). 

Ruby gems specs.gz is 2.1MB. A decade of gems I guess? 

Updating is not something done that often and the size after 10 years is still less than an average mp3. It doesn't seem like something needed for Hex or RubyGems even.

**Comment by ericmj** [comment]
The issue is that you need to download the full file every time the user fetches dependencies because you cannot be sure new versions have been published in between. Today it's 85kb for ~1400 entries so we need to find a more compact format than ETS files. Suggestions?

**Comment by tsloughter** [comment]
I'm confused, why do you have to fetch the index every time you download dependencies?

**Comment by ericmj** [comment]
Because we need the index to know which dependencies and what versions to fetch. We don't need to do it every time you fetch, we need to do it when dependencies are updated or you are fetching when some dependencies are not locked yet.

**Comment by tsloughter** [comment]
I always considered this the user's responsibility. The user must run an 'update' command to download the updated registry. Is this not what other package managers do?

**Comment by ericmj** [comment]
OS package managers require you to manually update the index, but I don't know of any developer package managers that require it. It seems like an unnecessary step which can be solved in a good way.

**Comment by tsloughter** [comment]
I was fairly sure that is what opam and cabal require. I could be wrong.

**Comment by ericmj** [comment]
That may be possible, but it doesn't mean we should follow suit. It's an extra manual step to perform that just feels unnecessary. That being said, rebar3 can have the manual step if it wants, there is a format for full index downloads in the proposal.

**Comment by mschae** [comment]
I just read through this and it's extremely interesting. 

This might be old news. But regarding the file size of the registry and the need to download it every time: why don't we just checksum the registry to a file and compare the local checksum with the remote checksum? That way we only have to download a few bytes every time we run mix and only have to download the entire thing when it changed. 

Might be that the frequency of new packages will be high enough so that this doesn't yield any results. Just wanted to float that idea by you...

**Comment by ericmj** [comment]
We already do conditional http requests with etag/if-none-match.

**Comment by mschae** [comment]
Way better. :)

Am Donnerstag, 2. Juli 2015 schrieb Eric Meadows-Jönsson :

> We already do conditional http requests with etag/if-none-match.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/42#issuecomment-118172627>.
>


-- 
*Michael Schaefermeyer*
michael.schaefermeyer@gmail.com
DE phone +49 (251) 590 8787
US phone +1 (415) 439 0430
about.me/mschae

**Comment by ferd** [comment]
Other than log formats, there are other ways to rebuild or modify indexes. One example would be to use hash-trees to only download the diffset (which is nicer than log formats when you *delete* elements -- log formats require tombstones or re-fetching the index snapshot when the last update took place before compaction) and to update this.

You could also try to just run a compressed table and see if that reduces the size:

```erlang
1> {ok, Reg} = ets:file2tab("registry").
{ok,20501}
2> file:write_file("registry-bin", term_to_binary(ets:tab2list(Reg), [{compressed,9}])).
ok
```
```
→ ls -al registry*
-rw-r--r--  1 ferd  staff  564489 22 Jun 20:44 registry
-rw-r--r--  1 ferd  staff  169754  2 Jul 19:34 registry-bin
```
Just doing this brings us to 30% of the current size on disk. Of course all of this would require at least a versioning scheme of the indexes so that hex clients are able to know when the format/protocol changed, but yeah.

There's a ton of good options to try before even reaching for a log database.

**Comment by ericmj** [comment]
@ferd I would be interested to read more about hash-trees and how to make it efficient over HTTP requests, if each change results in a separate HTTP request there will be an efficiency problem. Do you have any references to literature?

We already gzip the registry, there is no way to fetch it uncompressed:

```
-rw-r--r--   1 ericmj  staff  584938 Jul  1 16:36 registry.ets
-rw-r--r--   1 ericmj  staff  190156 Jul  1 16:36 registry.ets.gz
```

It seems like the `{compressed,9}` option is slightly more efficient than plain gzip, the problem is that it's undocumented so I don't even know which compression algorithm it uses which is bad because we need to document everything. The `compressed` option is documented and it uses gzip, but `{compressed,N}` is not.

**Comment by ferd** [comment]
For the hash tree algorithms, the one I'm always a fan of is the merkle tree. The trick is to build up a kind of hash *trie*:

```
               (Root)
                Inner
               /    \
              /      \
           (11)      (213)
 <<11,45,101,...>>   Inner
                    /     \
                   /       \
                (21)       (33)
     <<213,21,54,...>>     <<213,33,98,...>>
```
Each inner node also has a hash of all its children's hashes, such that you can easily transfer the top level (as an ETag for example) to know if there have been *any* modifications to the data set.

After that, you need to check the children at each level for their hashes and compare them in both trees. This ends up giving you a Log₂₅₅ diffing algorithm for each key. The issue, as you said, has to do with the back-and-forth between both ends.

The two big solutions to that include going to websockets to negotiate, or to have the client send up the first N levels of its tree, along with the root as an ETag. If the root matches, fine, send nothing back. If not, do the diff of the first N levels, send whatever makes sense there back as a patch-like response. If too many don't match, send a full new resource.

Frequent usage would amortize the cost more and more, but the tricky part is choosing how many nodes to send if you can't do back and forths between them. There's a bunch of libraries floating around to do that, to various levels.

**Comment by jcspencer** [comment]
@ferd While I do find this solution to be greatly effective if used infrequently, I can see the following problems with it in a production application:

* sending data backwards and forwards is not going to scale with a large number of concurrent clients (especially with the rate that hex adoption is growing)
* using this approach will require a dedicated server to conduct the negotiation (whereas @ericmj's first proposal would basically work on any HTTP server)
* reimplementation of this format in different languages would be a challenge for developers, compared to a simple binary implementation

What are your thoughts?

**Comment by ferd** [comment]
- sending the data forward and backwards should in theory be more efficient than a log-structured format. The point is that:
  - if everything is up to date, the cost is the same (trade a hash and check it, vs trading a log sequence number and checking it)
  - if only a few keys are missing, these are found in O(log n) time under the tree structure *no matter which is missing*. For an event-based replication system (i.e. logs), if an entry is missing, all missing events have to be replayed.
  - if any data gets rewritten or churned, a log-based data structure therefore risks sending more data than a tree would by replaying all the now-invalid events.
  - log storage can alleviate that with log compaction
  - however log compaction will drop old events that are no longer desired to be stored. For example, 'delete' operations -- they will require a tombstone under log storage, and the tombstone needs to be kept for a grace period. If it is cleared before replicas have synchronized, you corrupted your replicas forever, and they need to start from scratch again to shed the useless state
  - state-based replication does not require tombstones.
- It is true that the tree approach requires a more complex client. However, if you're on the Erlang VM, the complexity is the same given we can all reuse the same libraries.
- A state-based approach can be hybridized by forwarding updates as they come (in a PUSH) and having clients do repairs (as a PULL with the diff operation). It is the fanciest case, though.

In practice, I believe Hex is mostly append-only and rarely deletes data, so a log-based approach is unlikely to encounter the problems of event-based replication. In the worst case, a replica that doesn't sync for a while could hit one of the packages that is mutable for a 1h period, and keep it forever after it's been deleted off of Hex. There would then be no cheap way to detect or fix the issue.

I feel this window of opportunity is small enough not to worry too much about it, but whatever log structured format you pick, be very aware of its tombstoning periods when it does log compaction unless you want to corrupt replicas.

**Comment by jcspencer** [comment]
@ferd Thanks for such an in-depth explanation and clarification! I think you've convinced me :+1: 

I guess my last question is: what protocols can we use for the negotiation, and will they be supported on Heroku?

**Comment by ericmj** [comment]
All of this needs to be able to run on top of HTTP, FTP or other similar *simple* protocols. That's why we need a log structured registry format and cannot use fancy algorithms.

**Comment by ferd** [comment]
yeah. The private prototype I have would require to go over websockets at the very least and needs a concept of an active session. FTP is just overall terrible (especially for people behind firewalls or having to deal with NAT).

Log structure is conceptually a lot simpler. I'd recommend going that way at first -- a state-based mechanism can always be added at a later point in time without problem. If I can get permission to open-source my stuff, I could demo it to you guys, but no need to wait on it.

**Comment by jcspencer** [comment]
@ericmj does your original log-structured format spec still stand, or do you want to use a different spec?

**Comment by ericmj** [comment]
It's going to be the same idea with the addition that we will hash each
"chunk" of the log and reference the previous chunk with a hash that will a
create a hash chain that we can use to check for integrity and changes
further down the chain.

On Fri, Oct 16, 2015 at 11:13 PM, James Spencer <notifications@github.com>
wrote:

> @ericmj <https://github.com/ericmj> does your original log-structured
> format spec still stand, or do you want to use a different spec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/issues/42#issuecomment-148884462>.
>



-- 
Eric Meadows-Jönsson

**Comment by ferd** [comment]
^ that format cannot work with log compaction for a client to check their own data as you will be skipping around the hash chain when records are rewritten/crushed. As long as you're aware the data set can never shrink or be compacted, you're fine, though.

**Comment by ferd** [comment]
Even if it ends up not being used, for the sake of completeness in this discussions, here's a demo application doing state-based replication with merkle trees: https://github.com/heroku/sdiff.

It would need a protocol handler translating the primitives (listen/accept, connect, send, recv) into a websockets format and some TLS support, for example, but it shows the core protocol being in place.

**Comment by ericmj** [comment]
A proposal is up and I have a working implementation for hex_web.

https://github.com/hexpm/specifications/pull/10
https://github.com/hexpm/hex_web/tree/emj-new-registry
