### ISSUE TITLE
Maybe implement stronger privacy protections for package authors?

### ISSUE THREAD

**Issue by hex-doxxed** [hexpm/hex_web#433]
Hi, first of all, thanks for all the work on hex package manager and it's ecosystem. A great job!

New privacy policy and display of previously hidden account name has put me in a very uncomfortable and dangerous position due to my country of origin. Unfortunately, I wasn't prescient enough to register a pseudonymous username.

As an author and maintainer of several packages I'll be forced to abandon them and delete github repos if I won't be able to remove/change/hide the prominently featured username.

Would you please consider implementing stronger privacy protections for authors of your packages?

Apart of the username issue, there is a question of historical records of maintainers names, project links, etc. I understand the need for immutability of code in packages (left-pad fiasco) but I feel there is no need to keep persistent records of maintainer name and links in previous package versions if there is a need to remove them. This won't break builds. 

I'm posting this from an anonymous account. Thank you for considering my request, I'm sure there are a lot of people in a similar position.

**Comment by ericmj** [comment]
The existing package artifacts can not change and that includes the package metadata. These artifacts and the associated metadata have been copied to mirrors and user systems. Unfortunately any information in them should be seen as public forever.

The changes in the privacy policy affects the display of your email address and package ownership, this information is not included in the package artifacts. There is nothing in the package metadata that associates the artifact with your Hex.pm account unless you add it to the metadata. 

You can hide your email address on the dashboard, there you can also change settings such as your profile picture and full name. If you want to change your username or anything else not available through the dashboard you can contact support@hex.pm and we will be able to help you with that.

Does that alleviate your concerns? If not, please let us know in this issue or if there is anything you are not comfortable with sharing publicly you can email support@hex.pm.
