### ISSUE TITLE
Password reset doesn't complain about non existing account

### ISSUE THREAD

**Issue by msoedov** [hexpm/hex_web#437]
I tried to reset password with unregistered email and I got confusing message:
```
You should receive an email shortly with a link to reset your password.
```
Eventually I figure out that I've never been registered on hexpm. However this is still confusing.

Steps to reproduce:
1. Go to reset password page
2. Use some random email foo@bar.com

**Comment by ericmj** [comment]
I understand that it is confusing but unfortunately we need to keep this behaviour due to privacy concerns.

If we gave a different message to emails that were not registered it could be used to guess which emails are in use on hex.pm and we do not allow this in our privacy policy.

**Comment by josevalim** [comment]
@ericmj one thing you could do is to clarify the message: "If this account has been registered in Hex, you should receive an email shortly with a link to reset your password".

**Comment by ericmj** [comment]
> one thing you could do is to clarify the message: "If this account has been registered in Hex, you should receive an email shortly with a link to reset your password".

Sounds good.
