### ISSUE TITLE
Have to click twice to get to documentation

### ISSUE THREAD

**Issue by jcelliott** [hexpm/hex_web#438]
Recently something changed so that I have to click twice in the sidebar to get to actual documentation. It used to go to the relevant page on the first click, and it would also expand the navigation in the sidebar. Now the first click expands the navigation for that section and you have to click on "Top" to actually see the documentation. It's a minor issue, but annoying. Was this a deliberate change, or did something break?

**Comment by ericmj** [comment]
This was intentionally changed in ex_doc [1]. If you want to discuss it please open an issue there.

[1] https://github.com/elixir-lang/ex_doc/
