### ISSUE TITLE
Show latest *stable* version by default on package page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#451]
This page https://hex.pm/packages/postgrex should show 0.12.1 even though 1.0.0-rc.1 is the latest release.

**Comment by ericmj** [comment]
Should we also filter away retired package?

It can be a good idea for postgrex for example, but it would be bad if you retire for deprecation or rename and only retire the latest release and we don't show that release.

/cc @josevalim

**Comment by josevalim** [comment]
I am not sure we should change the behaviour here. For example, take Ecto, I would prefer if developers saw the pre-releases first. If we change this, it means no prerelease would be shown, as they would always come last?

I also would not change the ordering if a package was retired. So I wouldn't change anything. This particular problem with postgrex will be solved as soon as we retire the release candidates.

**Comment by wojtekmach** [comment]
> This page https://hex.pm/packages/postgrex should show 0.12.1 even though 1.0.0-rc.1 is the latest release.

:+1: from me. This would also be consistent with https://hexdocs.pm/postgrex

> Should we also filter away retired releases*?

You mean that on https://hex.pm/packages/postgrex we would simply not show retired releases? I'd still show them so that when a user locked on a particular release, he/she can see on the website that it got retired. It's a separate issue, but maybe we should adjust client to show a warning if user is using a retired release?

> Or should we add a way to retire all releases for deprecation/rename?

Yeah, I can see that could be useful.

>  I would prefer if developers saw the pre-releases first (...) I also would not change the ordering if a package was retired

:+1:

> This particular problem with postgrex will be solved as soon as we retire the release candidates.

I'm confused, 1.0.0-rc.0 and 1.0.0-rc.1 are already retired

**Comment by josevalim** [comment]
Oh, I understand the issue now. Yes, I agree that the package version shown at the top of the page should shown the latest, non-prerelease, non-retired version. Everything else should stay as is.

My previous comment was related exclusively to the list of versions at the bottom. I wouldn't change anything there.

**Comment by josevalim** [comment]
If the latest non-prerelease is retired, then we should show it at the top, because it either means it is important information (you shouldn't use the latest) or the whole package is retired. Most times, you will release a new package right after you retire a current version.

**Comment by ericmj** [comment]
To clarify, I am only talking about the default version we show at the top of the page and the associated for that release on the page. I am happy with the list of versions we show now on hex.pm and it will stay the same.

> If the latest non-prerelease is retired, then we should show it at the top, because it either means it is important information (you shouldn't use the latest) or the whole package is retired. Most times, you will release a new package right after you retire a current version.

I like this, it makes sense to make a distinction between if the latest non-prerelease is retired or not.

**Comment by ericmj** [comment]
Fixed in emj_retire PR.
