### ISSUE TITLE
Show release retirement status on /api/packages/:name

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_web#452]
See e.g.: https://hex.pm/api/packages/postgrex, it isn't shown that 1.0.0-rc.0 is retired.
We only see it here: https://hex.pm/api/packages/postgrex/releases/1.0.0-rc.0

**Comment by ericmj** [comment]
Should we show the full retired struct (message/status) or only `retired: true|false`?

**Comment by wojtekmach** [comment]
good question, do you have a preference? I think both option sound good. Returning a full retired struct would keep the api more unified, but just `retired` is definitely shorter.

**Comment by ericmj** [comment]
My concern is that I want to keep the releases list small. You should query for individual releases if you want more information. But given that not many releases should be retired I guess we can include the struct.
