### ISSUE TITLE
Word-wrap long package names

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_web#453]
See:

- https://hex.pm/packages/nerves_system_qemu_arm - see dependencies
- https://hex.pm/packages/nerves_toolchain_arm_unknown_linux_gnueabihf - see package name at the top

**Comment by sotojuan** [comment]
It seems it's the `line-height` that makes it look bad. Here's what the second example looks like with `line-height: 55px`:

http://i.imgur.com/C1xe59A.png

**Comment by ericmj** [comment]
@sotojuan Nice find. I think for the title we want to show the whole name with the line-height fix and for dependencies we want to wrap it with an ellipsis.
