### ISSUE TITLE
Normalize repository field

### ISSUE THREAD

**Issue by sotojuan** [hexpm/hex_web#456]
This may fit better in the actual Hex repo—let me know.

Currently packages don't have a consistent field for their associated repository—Hex uses whatever the put in the `mix.exs` file. This causes problems for people trying to parse Hex data for third party services:

* GitHub vs Github vs github
* The above vs GitLab vs BitBucket vs etc

Sure, the latter is rare and the former can be fixed by forcing `downcase` on the keys before parsing, but it's not very user friendly. I'd prefer just a `repo` key with the value being a string of the URL.

**Comment by ericmj** [comment]
We don't have any plans to add a special repo key at this time. It would indeed be a slight improvement to have a special key for the repo but the improvement is not big enough to have every single package publisher update their metadata.

Maybe we can include this change later if we do other changes to the metadata.

For related discussion: https://github.com/hexpm/hex_web/issues/443

**Comment by sotojuan** [comment]
That's fair—just wanted to know your opinion on the issue. Thanks!
