### ISSUE TITLE
upgrade to run on elixir 1.4

### ISSUE THREAD

**Issue by LTheGreats** [hexpm/hex_web#471]
I looked at the build pack and it said that it was using elixir 1.3.3 however, I think it would be better to upgrade and use elixir 1.4 instead

**Comment by wojtekmach** [comment]
Thanks @LTheGreats for reporting.

There's a couple of other things that would be good to do while at it:
- update `.travis.yml`
- update `mix.exs` and remove applications (as they're inferred from deps in v1.4)
- fix v1.4 TODOs

PR is welcome!

**Comment by wojtekmach** [comment]
Closed by/in favor of https://github.com/hexpm/hex_web/pull/472 https://github.com/hexpm/hex_web/pull/473
