### ISSUE TITLE
Split HTML sanitisation engine and template helpers into another project

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#69]
As discussed by @ericmj in #26, and on IRC.

It would allow for much more dedicated testing, and allow for re-use in projects other than hex_web.

/cc @chrismccord @josevalim

**Comment by ericmj** [comment]
Closing since it has been done with phoenix and we will be migrating to it.

**Comment by jcspencer** [comment]
Will we maintain to keep the same sanitization API on the hex_web side, or change the hex_web sanitization API to suit that of phoenix_html?

**Comment by ericmj** [comment]
We will use the one from phoenix.
