### ISSUE TITLE
Serve Rebar 3 packages with Hex

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex_web#74]
Based on a discussion on IRC with @tsloughter (and to some extent @ferd), this is a proposal and discussion to have Rebar 3 packages stored and served from Hex.

## Rationale

Hex already provides the whole structure for publishing and serving packages. Also, since Hex aims to be the package manager for the whole Erlang Ecosystem, with better tooling for Erlang already on the way, it makes sense for Rebar 3 and Hex teams to join efforts in the packages department.

## Precompiled packages

Today Hex currently just stores the source code for packages. On the other hand, Rebar packages are actually precompiled packages (with BEAM files) per erts version.

Although those approaches may look conflicting at first, Rebar packages are a natural expansion of the Hex model. Once a package (its source) is published, the author (or a build service) can push precompiled versions of the package based on the erts version. In simpler words, we will extend Hex so a package can have multiple precompiled versions.

Since the Rebar team is currently only interested in precompiled versions, they can fetch the package registry, filter the registry based on the current erts version, and just download those packages. In the future, the Rebar team may also consider supporting source-based packages, which may be an option for compiling packages with C dependencies.

While the Elixir tooling still requires the source, which will continue to be available in Hex, nothing stops Elixir from also using precompiled packages in the future, saving in compilation time.

## Hex overview

This is an overview of how Hex works today and the changes that will be done to support precompiled packages. This is also the API Rebar will use for fetching precompiled packages.

### S3

The registry and packages are currently stored in S3. The available endpoints are:

  * `/registry.ets.gz` - gzipped ets file
  * `/tarballs/PACKAGE-VERSION.tar` - package tarball

We propose a new end-point, `/tarballs/erts/6.2/cowboy-1.0.0.tar`, to be added for precompiled package tarball per erts as part of this discussion.

The tarball contents for precompiled packages is the same as the package tarball except it also contains precompiled `.beam` files.

### The registry

The registry is an ETS table generated with `ets:tab2file/2`. The items are:

  * `{'$$version$$', Version}` - the registry version
    - Version: integer, incremented on breaking changes

  * `{Package, [Versions]}` - all releases of a package
    - Package: binary string
    - Versions: list of binary string semver versions

  * `{{Package, Version}, [Deps, Checksum, Builds | _]}` - a package release's dependencies
    - Package: binary string
    - Version: binary string semver version
    - Deps: List of dependencies
      - Dep: [Name, Requirement, Optional, App]
        - Name: binary package name
        - Requirement: binary Mix.Version requirement
        - Optional: boolean true if it's an optional dependency
        - App: binary OTP application name
    - Checksum: Binary hex encoded sha256 checksum of package, see below
    - Builds: List of builds
      - Build: [Params]
        - Params: List of parameters
          - Param: [{Key, Value}]
            Key: binary
            Value: binary

The `Builds` field does not currently exist in the registry and we propose it to be added as part of this discussion. We have designed it as a proplist in case we want to support types of builds in the future.

### Package tarball
 
The package tarball contains the following files:

  * VERSION
    - the tarball version as a single ASCII integer
 
  * CHECKSUM
    - sha256 hex encoded checksum of tarball
    - `sha256(<<contents(VERSION)/binary, contents(metadata.exs)/binary, contents(contents.tar.gz)/binary)`
 
  * metadata.exs
    - Erlang term file
 
  * contents.tar.gz
    - gzipped tarball with package contents

## Next steps

This provides an overview of the current API and the work we are going to do for supporting precompiled packages in Hex. It also specifies the API that Rebar 3 will consume.

@tsloughter and @ferd, please validate if this API is enough for you to get started and if there is anything we should change and/or clarify in the short term. Also let us know if you need help or want to discuss anything on the Rebar 3 side of things.

**Comment by jcspencer** [comment]
Has there been any progress on this?
If not, what are the key parts that have to be put into place to make this possible?

**Comment by jcspencer** [comment]
pinging @ericmj @josevalim @tsloughter @ferd

**Comment by ericmj** [comment]
@jcspencer It's an ongoing process. For now there is nothing that has to be done.

**Comment by tsloughter** [comment]
Mix has environments and rebar3 has profiles, wouldn't it be good to separate deps by profile like they can be in configs instead of just required or optional?

**Comment by ericmj** [comment]
@tsloughter I would like to read on how rebar3 profiles work, do you have documentation on them?

In mix all dependencies run in the production environment and only prod deps (and deps that hasn't specified an environment) are included in the package. If we look at ecto's mix.exs file https://github.com/elixir-lang/ecto/blob/master/mix.exs#L33-L40 you can see that some deps have `only: :docs`. They wont be included in the package and consumers of ecto wont fetch them. But when developing ecto the packages will be fetched. With this approach I think we only need to separate by env/profile in the clients and we don't need to add this to hex.

Does that make sense?

**Comment by tsloughter** [comment]
Profiles http://www.rebar3.org/v3.0/docs/profiles

And yea, I tried to think of a scenario that makes sense to fetch the deps of a dep for a random profile but couldn't... So probably it is probably good as is.

**Comment by ericmj** [comment]
The metadata format has been changed to erlang term files. It still expects the same keys and values as described in https://github.com/hexpm/hex_web/issues/74#issuecomment-67581618, except that maps will be deprecated in favor of proplists to support older OTP versions. All keys should be binaries, atoms are not allowed in the metadata.

**Comment by ericmj** [comment]
In this gist https://gist.github.com/ericmj/ddfe9879ecf3b6572af3 is the specification for precompiled packages and the additions to the package metadata. Unless you have any comments I am going to start implementing this in the next few days.

/cc @tsloughter @ferd

**Comment by ferd** [comment]
- Are your endpoints key/values sorted, or do you expect combinatorial explosion of parameters in paths? Either have explicit path hierarchies or an explicit order to them

**Comment by ericmj** [comment]
Parameter keys in the endpoint should be sorted according to ASCII. I.e. the "arch" key should appear before the key "erts".

**Comment by tsloughter** [comment]
I'd suggest (for precompiled packages) requiring `/arch/<type>/erts/<vs>` where for packages that only have BEAM code type is `generic`.

**Comment by josevalim** [comment]
What about not sending arch if it is only beams?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by tsloughter** [comment]
I just figured a built package always having an arch and an erts would make it more consistent.

**Comment by josevalim** [comment]
@tsloughter but are you going to prebuild it for all archs then? or you will have another tag saying it is beam only?

**Comment by tsloughter** [comment]
@josevalim hm? Being arch `generic` would mean that it is beam only.

**Comment by ericmj** [comment]
Are we only going to allow predefined parameters such as "arch" and "erts"? My first idea was to allow any parameters and it would be up to build tools to use them however they like. However, just allowing certain predefined keys may be better because all build tools using hex should agree on parameter conventions so that everyone can make use of precompiled packages regardless of the creator.

Only allowing predefined keys also means that we don't have to sort keys, we can just decide the order that makes the most sense.

As for the "arch" discussion, lets table it until someone is building based on architecture? We can make the decision then and use redirects to ensure backwards compatibility.

**Comment by tsloughter** [comment]
I'd be fine with predefined keys. But if we went that way then I'd argue for always having `arch` and `erts` requires for prebuilt packages :)

**Comment by josevalim** [comment]
Another reason for not including arch if the value is going to be generic is space. Most of the packages will have no arch. If we have 100_000 package versions, how much space we will save by not including it?

**Comment by josevalim** [comment]
It just feels very weird to include information which can be represented by its absence.

**Comment by tsloughter** [comment]
Not sure how the size matters, it is negligible. I just thought it would make it uniform instead of requiring a special case. Either way works.

**Comment by josevalim** [comment]
To me adding a "generic" arch is the special case. :) Also, if we decide to show those "tags" on the website, it feels weird to have `arch: generic` in there, so my vote is to skip it.

**Comment by tsloughter** [comment]
Hehe, it feels weird to me to not have `arch: generic` on the website since then the user has to know that the lack of `arch` means `generic` :)

**Comment by josevalim** [comment]
@tsloughter hahaha! :D it depends also if we are going to have multiple tags or not. Because people may push a tag `gcc: 5.1` and then people will automatically learn that the lack of a tag means you don't care.

**Comment by ericmj** [comment]
Update: Added build_tools to release metadata and to registry. Next step is to create a new registry format for rebar3.

**Comment by ericmj** [comment]
Specifications listed in this issues are located here: https://github.com/hexpm/hex_web/tree/master/specifications. The final missing part is the HTTP API which I will be working on documenting next.
