### ISSUE TITLE
Display latest package version in search results

### ISSUE THREAD

**Issue by alexrp** [hexpm/hex_web#79]

**Comment by JamesS237** [comment]
Working! Just a bit of cleaning up left :smile: 

![screen shot 2015-01-01 at 4 24 23 pm](https://cloud.githubusercontent.com/assets/860934/5591711/84556c4c-91d2-11e4-8006-55b2533519ba.png)

**Comment by JamesS237** [comment]
Done! See #82.
//cc @ericmj
