### ISSUE TITLE
Phase out PATCH "users/:name"

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#94]
The password reset functionality of this route has been replaced by `/api/users/:user/reset`, and the email reset functionality is forthcoming.

If this is correct, I'll open up a PR.

@josevalim @ericmj

**Comment by ericmj** [comment]
Yeah, but we need to keep the functionality for at least one month after the release of the next hex version.

**Comment by jcspencer** [comment]
Any idea when we expect to push a new release?

**Comment by ericmj** [comment]
No idea, waiting for a response on the erlang-questions list so we can fix certificate verification.

**Comment by jcspencer** [comment]
As Hex v0.7.0 was released on 2015/02/15, we *should* be able to phase this out at some point after March 15th.

Do we have any way to check the current usage statistics of `PATCH "users/:name"` vs. `POST "users/:name/reset"`?

**Comment by ericmj** [comment]
I can try to get some usage statistics from Heroku and S3 logs. But I think we should remove `PATCH` ASAP after the 15th since it's a potential security issue.

**Comment by jcspencer** [comment]
I agree. If you don't think it's too much of a user inconvenience, I think removing it on the 15th is a good idea.

**Comment by jcspencer** [comment]
Fixed in #102
