### ISSUE TITLE
Add the ability to reset account email address

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#97]
Now that #22 (password reset via email) has been implemented, and client support is available in the master branch of the Hex client, we should now be able to implement the ability to reset email addresses for accounts.

I have some ideas of how this could be done; Sadly, sending a link to reset page to an existing email address is useless in this situation, so it requires different logic to resetting account passwords.

@ericmj and @josevalim, what are your thoughts on this?

**Comment by ericmj** [comment]
The user can still change email with a reset link if they control their old email. If they lost their email they are out of luck and need to convince an admin that it's their account. No way around that unfortunately.

**Comment by jcspencer** [comment]
Sounds like a reasonable way to solve it :+1:

**Comment by jcspencer** [comment]
@ericmj Any specific reason for closing this?

**Comment by ericmj** [comment]
You can only change your email if you control the old email. Because of that this is not a high priority issue. If you want to work on it please go ahead.
